import { readFileSync } from 'node:fs';
import { describe, it, expect } from 'vitest';
import type { ModeDef, ModeModifier } from '../src/rules/types';

/*
 * MODES vs PRINT — the 115 findings of the 2026-09-15 modes audit, one leg each.
 *
 * Every leg reads a SEED file, never public/core.json. That is the whole point: core.json is
 * regenerated by `npm run data` from these three sources, so a leg that read the generated copy
 * would pass on a file that the next regen throws away. Proving the SOURCE proves the ship.
 *
 *   scripts/data/consumable-modes.json  item modes (an array)
 *   scripts/data/toggle-modes.json      everything else (an id-keyed object)
 *   scripts/data/effect-backfill.json   three records that exist ONLY as overlay rows
 *
 * Each finding was adversarially confirmed against the printed text (live Archives where the local
 * prose is scrape-damaged) before it reached here. Legs marked `it.todo` are the findings whose fix
 * needs a change outside this lane — they are named so the count stays honest, not silently dropped.
 */

const consumable = JSON.parse(readFileSync('scripts/data/consumable-modes.json', 'utf8')) as ModeDef[];
const toggle = JSON.parse(readFileSync('scripts/data/toggle-modes.json', 'utf8')) as Record<string, ModeDef>;

/** An item mode by id, from the array file. Throws rather than returning undefined so a renamed
 *  record fails loudly instead of every expect silently reading `undefined`. */
function item(id: string): ModeDef {
  const m = consumable.find((x) => x.id === id);
  if (!m) throw new Error(`no item mode "${id}" in scripts/data/consumable-modes.json`);
  return m;
}

function mode(id: string): ModeDef {
  const m = toggle[id];
  if (!m) throw new Error(`no toggle mode "${id}" in scripts/data/toggle-modes.json`);
  return m;
}

const mods = (m: ModeDef): ModeModifier[] => m.modifiers ?? [];
/** The first modifier on `target` (optionally narrowed by `detail`). */
const modFor = (m: ModeDef, target: string, detail?: string): ModeModifier | undefined =>
  mods(m).find((x) => x.target === target && (detail === undefined || x.detail === detail));

/** The overlay row that CREATES a mode — for the three records with no seed-file entry. */
let overlayCache: { category: string; id: string; field?: string; create?: boolean; value?: unknown }[] | null = null;
function overlayRows() {
  overlayCache ??= JSON.parse(readFileSync('scripts/data/effect-backfill.json', 'utf8')) as typeof overlayCache;
  return overlayCache!;
}
function overlayMode(id: string): ModeDef {
  const row = overlayRows().find((r) => r.category === 'modes' && r.id === id && r.create);
  if (!row?.value) throw new Error(`no create row for modes/${id} in scripts/data/effect-backfill.json`);
  return row.value as ModeDef;
}
/** A FIELD row amending a record the overlay also creates. A field the create row already carries is
 *  a different row from one added later, and reading the create row alone would miss the later one. */
function overlayField(id: string, field: string): unknown {
  const row = overlayRows().find((r) => r.category === 'modes' && r.id === id && r.field === field);
  if (!row) throw new Error(`no "${field}" row for modes/${id} in scripts/data/effect-backfill.json`);
  return row.value;
}

describe('consumable-modes.json — item modes', () => {
  it('antivenom potion: the Fortitude bonus is an ITEM bonus and the note prints the DC 10 flat check', () => {
    // bug 2026-09-15: modes vs print
    const m = item('item-antivenom-potion');
    expect(mods(m)[0].type).toBe('item');
    expect(m.note).toContain('DC 10 flat check');
  });

  it('apricot of bestial might: resistance 8 to physical reaches the IWR lane, and the flat check has its DC', () => {
    // bug 2026-09-15: modes vs print
    const m = item('item-apricot-of-bestial-might');
    expect(m.resistances).toEqual([{ type: 'physical', value: 8 }]);
    expect(m.note).toContain('DC 5 flat check');
  });

  it('clawed bracers: the climb Speed 20 is granted, not prose', () => {
    // bug 2026-09-15: modes vs print
    expect(item('item-clawed-bracers').speeds).toEqual({ climb: 20 });
  });

  it('cloud buns (greater): fly Speed 30 capped at your land Speed', () => {
    // bug 2026-09-15: modes vs print
    expect(item('item-cloud-buns-greater').speeds).toEqual({ fly: 'min(30,@actor.speed.land)' });
  });

  it('candle of inflamed passions: the holder carries the -1 status penalty too', () => {
    // bug 2026-09-15: modes vs print
    const m = item('item-candle-of-inflamed-passions');
    const mod = modFor(m, 'save');
    expect(mod).toMatchObject({ type: 'status', value: -1 });
    expect(mod?.detail).toBeUndefined(); // all three saves
    expect(mod?.appliesWhen).toContain('emotion effects');
  });

  it("Cayden's brew: the breath weapon's DC 25 Fortitude save is in the note", () => {
    // bug 2026-09-15: modes vs print
    expect(item('item-caydens-brew').note).toContain('DC 25 Fortitude');
  });

  it("Cayden's brew (double): DC 31 Fortitude", () => {
    // bug 2026-09-15: modes vs print
    expect(item('item-caydens-brew-double').note).toContain('DC 31 Fortitude');
  });

  it("Cayden's brew (triple): DC 40 Fortitude", () => {
    // bug 2026-09-15: modes vs print
    expect(item('item-caydens-brew-triple').note).toContain('DC 40 Fortitude');
  });

  it('egg cream fizz: the +5-foot item bonus to Speed is a modifier, and the false "no speed target" claim is gone', () => {
    // bug 2026-09-15: modes vs print
    const m = item('item-egg-cream-fizz');
    expect(modFor(m, 'speed')).toMatchObject({ type: 'item', value: 5 });
    expect(m.note).not.toContain('not a mode-modifier target');
  });

  /* Finding 9 asked for an unconditional -10 ft speed modifier on the deadweight mutagens; finding 10,
   * covering the same four grades, ruled the opposite — the app already applies Encumbered's -10 ft
   * from the condition, so a mode modifier would count it twice. Finding 10 is what shipped. */
  it.todo('deadweight mutagen (greater): -10 ft speed modifier — NOT APPLIED, contradicted by finding 10 (double-count with the Encumbered condition)');

  it('deadweight mutagen (all four grades): the mode APPLIES Encumbered itself and adds no speed modifier', () => {
    // bug 2026-09-15: modes vs print
    /* The note used to send the player to the Conditions panel to add Encumbered by hand — the app
     * handing its own job back. `conditions` is the carrier; the -10 ft and Clumsy 1 still come from
     * the condition, which is why finding 10's "no speed modifier" half is unchanged. */
    for (const grade of ['lesser', 'moderate', 'greater', 'major']) {
      const m = item(`item-deadweight-mutagen-${grade}`);
      expect(m.conditions).toEqual([{ id: 'encumbered' }]);
      expect(m.note).not.toContain('Conditions panel');
      expect(m.note).toContain('Encumbered');
      expect(modFor(m, 'speed')).toBeUndefined();
    }
  });

  it("dinosaur boots: Enlarge's +2 status to melee damage and the Clumsy 1 instruction", () => {
    // bug 2026-09-15: modes vs print
    const m = item('item-dinosaur-boots');
    expect(modFor(m, 'damage')).toMatchObject({ type: 'status', value: 2 });
    expect(m.note).toContain('Clumsy 1');
  });

  it('dinosaur boots (greater): 4th-rank Enlarge is +4, Huge, reach +10 ft', () => {
    // bug 2026-09-15: modes vs print
    const m = item('item-dinosaur-boots-greater');
    expect(modFor(m, 'damage')).toMatchObject({ type: 'status', value: 4 });
    expect(m.note).toContain('Huge');
    expect(m.note).toContain('10 feet');
  });

  it('delve scale: burrow Speed 15', () => {
    // bug 2026-09-15: modes vs print
    expect(item('item-delve-scale').speeds).toEqual({ burrow: 15 });
  });

  it('dragonfly potion: fly Speed equal to your land Speed, plus low-light vision', () => {
    // bug 2026-09-15: modes vs print
    const m = item('item-dragonfly-potion');
    expect(m.speeds).toEqual({ fly: '@actor.speed.land' });
    expect(m.senses).toEqual([{ name: 'low-light-vision' }]);
  });

  it("diplomat's charcuterie and the other daily-preparations modes do NOT survive rest", () => {
    // bug 2026-09-15: modes vs print
    for (const id of [
      'item-diplomats-charcuterie',
      'item-auric-noodles',
      'item-menders-soup',
      'item-trackers-stew',
      'item-phantom-roll',
      'item-candle-of-invocation',
    ]) {
      expect(item(id).survivesRest).toBeUndefined();
    }
  });

  it('mana-rattler liniment: the fangs carry +1 poison', () => {
    // bug 2026-09-15: modes vs print
    expect(item('item-mana-rattler-liniment').strikeDamage).toEqual([
      { type: 'poison', flat: 1, strikeName: 'Fangs', note: 'Mana-rattler liniment' },
    ]);
  });

  it("heartblood ring: the -2 status penalty against the vampire's powers exists at all", () => {
    // bug 2026-09-15: modes vs print
    const m = item('item-heartblood-ring');
    const penalty = mods(m).find((x) => x.value === -2);
    expect(penalty).toMatchObject({ target: 'save', type: 'status' });
    expect(penalty?.appliesWhen).toContain('vampire');
  });

  it('ghost fowl porridge: resistance 3 to physical', () => {
    // bug 2026-09-15: modes vs print
    expect(item('item-ghost-fowl-porridge').resistances).toEqual([{ type: 'physical', value: 3 }]);
  });

  /* Findings 19, 20 and 21 proposed three different shapes for the same three cups (six per-blend
   * modifiers / modifiers:[] / one conditional modifier). Finding 21's single-modifier shape shipped
   * for all three, which closes the defect all three named: the bonus is Recall Knowledge only. */
  it('insight coffee (lesser): +2 scoped to Recall Knowledge, and the strategic strike d8 upgrade is stated', () => {
    // bug 2026-09-15: modes vs print
    const m = item('item-insight-coffee-lesser');
    expect(modFor(m, 'skill')).toMatchObject({ type: 'item', value: 2 });
    expect(modFor(m, 'skill')?.appliesWhen).toContain('Recall Knowledge');
    expect(m.note).toContain('strategic strike');
  });

  it('insight coffee (moderate): the note scopes the bonus to Recall Knowledge, not every check', () => {
    // bug 2026-09-15: modes vs print
    const m = item('item-insight-coffee-moderate');
    expect(m.note).toContain('Recall Knowledge');
    expect(m.note).not.toContain('+3 item bonus to checks with the single skill');
    expect(modFor(m, 'skill')).toMatchObject({ value: 3 });
  });

  it('insight coffee (greater): +4 conditional on Recall Knowledge', () => {
    // bug 2026-09-15: modes vs print
    const m = item('item-insight-coffee-greater');
    expect(modFor(m, 'skill')).toMatchObject({ type: 'item', value: 4 });
    expect(modFor(m, 'skill')?.appliesWhen).toContain('Recall Knowledge');
  });

  it('gecko potion: the +1 to the Reflex DC against Disarm is modelled like its siblings', () => {
    // bug 2026-09-15: modes vs print
    const mod = modFor(item('item-gecko-potion'), 'save', 'reflex');
    expect(mod).toMatchObject({ type: 'item', value: 1 });
    expect(mod?.appliesWhen).toContain('Disarm');
  });

  it("golden liberator's feather: fly Speed 50", () => {
    // bug 2026-09-15: modes vs print
    expect(item('item-golden-liberators-feather').speeds).toEqual({ fly: 50 });
  });

  it('moon blossom tea: the +2 lands on the initiative target, unconditionally', () => {
    // bug 2026-09-15: modes vs print
    const m = item('item-moon-blossom-tea');
    expect(mods(m)).toEqual([{ target: 'initiative', type: 'item', value: 2 }]);
  });

  it('phoenix cinder: half-level fire resistance and the fire immunity reach the IWR list', () => {
    // bug 2026-09-15: modes vs print
    const m = item('item-phoenix-cinder');
    expect(m.resistances).toEqual([{ type: 'fire', value: 'floor(@actor.level/2)' }]);
    expect(m.immunities).toEqual(['fire']);
  });

  it('phoenix cinder: the +1 circumstance covers AC as well as saves ("or any other defense")', () => {
    // bug 2026-09-15: modes vs print
    const mod = modFor(item('item-phoenix-cinder'), 'ac');
    expect(mod).toMatchObject({ type: 'circumstance', value: 1, appliesWhen: 'against fire' });
  });

  it('pallesthetic mutagen: echolocation and tremorsense are real senses', () => {
    // bug 2026-09-15: modes vs print
    expect(item('item-pallesthetic-mutagen').senses).toEqual([
      { name: 'echolocation', range: 40, acuity: 'precise' },
      { name: 'tremorsense', range: 60, acuity: 'imprecise' },
    ]);
  });

  it('ommatophoric mutagen: low-light vision is a sense', () => {
    // bug 2026-09-15: modes vs print
    expect(item('item-ommatophoric-mutagen').senses).toEqual([{ name: 'low-light-vision' }]);
  });

  it('theatrical mutagen (lesser): +5-foot status bonus to Speed', () => {
    // bug 2026-09-15: modes vs print
    expect(modFor(item('item-theatrical-mutagen-lesser'), 'speed')).toEqual({ target: 'speed', type: 'status', value: 5 });
  });

  it('theatrical mutagen (moderate): +5-foot status bonus to Speed', () => {
    // bug 2026-09-15: modes vs print
    expect(modFor(item('item-theatrical-mutagen-moderate'), 'speed')).toEqual({ target: 'speed', type: 'status', value: 5 });
  });

  it('theatrical mutagen (greater): +10-foot status bonus to Speed', () => {
    // bug 2026-09-15: modes vs print
    expect(modFor(item('item-theatrical-mutagen-greater'), 'speed')).toEqual({ target: 'speed', type: 'status', value: 10 });
  });

  it('theatrical mutagen (major): +10-foot status bonus to Speed', () => {
    // bug 2026-09-15: modes vs print
    expect(modFor(item('item-theatrical-mutagen-major'), 'speed')).toEqual({ target: 'speed', type: 'status', value: 10 });
  });

  it('spiderfoot brew (lesser): climb Speed 15', () => {
    // bug 2026-09-15: modes vs print
    expect(item('item-spiderfoot-brew-lesser').speeds).toEqual({ climb: 15 });
  });

  it('spiderfoot brew (moderate): climb Speed 20', () => {
    // bug 2026-09-15: modes vs print
    expect(item('item-spiderfoot-brew-moderate').speeds).toEqual({ climb: 20 });
  });

  it('spiderfoot brew (greater): climb Speed 25', () => {
    // bug 2026-09-15: modes vs print
    expect(item('item-spiderfoot-brew-greater').speeds).toEqual({ climb: 25 });
  });

  it('statue skin salve: resistance 3 to piercing and slashing', () => {
    // bug 2026-09-15: modes vs print
    expect(item('item-statue-skin-salve').resistances).toEqual([
      { type: 'piercing', value: 3 },
      { type: 'slashing', value: 3 },
    ]);
  });

  /* The four silvertongue grades carry the printed -2 to EVERY Lore as a `lore:*` wildcard detail.
   * modeMatches (src/rules/modes.ts) has to learn that spelling for the number to move — until it
   * does, the modifier is inert rather than wrong, and the print is at least on the record. */
  for (const grade of ['lesser', 'moderate', 'greater', 'major'] as const) {
    it(`silvertongue mutagen (${grade}): the -2 item penalty to every Lore is encoded`, () => {
      // bug 2026-09-15: modes vs print
      const m = item(`item-silvertongue-mutagen-${grade}`);
      expect(modFor(m, 'skill', 'lore:*')).toEqual({ target: 'skill', detail: 'lore:*', type: 'item', value: -2 });
      expect(m.note).not.toContain('apply it by hand');
    });
  }

  it('wolfjaw armor: the jaws deal +1 cold', () => {
    // bug 2026-09-15: modes vs print
    expect(item('item-wolfjaw-armor').strikeDamage).toEqual([
      { type: 'cold', flat: 1, strikeName: 'Jaws', note: 'Witchwarg jaws' },
    ]);
  });

  it('sea touch elixir (greater): a 24-hour elixir survives the night', () => {
    // bug 2026-09-15: modes vs print
    expect(item('item-sea-touch-elixir-greater').survivesRest).toBe(true);
  });

  it('phantom roll: cleared by the daily preparations its duration names', () => {
    // bug 2026-09-15: modes vs print
    expect(item('item-phantom-roll').survivesRest).toBeUndefined();
  });

  it('vermin repellent (major): a plain success is still frightened 1, at DC 35', () => {
    // bug 2026-09-15: modes vs print
    const note = item('item-vermin-repellent-agent-major').note ?? '';
    expect(note).toContain('DC 35 Will save');
    expect(note).toContain('critical success');
  });

  it('vermin repellent (moderate): DC 24, with the critical success degree spelled out', () => {
    // bug 2026-09-15: modes vs print
    const note = item('item-vermin-repellent-agent-moderate').note ?? '';
    expect(note).toContain('DC 24');
    expect(note).toContain('Critical Success');
  });

  it('resolute mind wrap: the reaction itself grants +1 to the triggering Will save', () => {
    // bug 2026-09-15: modes vs print
    expect(item('item-resolute-mind-wrap').note).toContain('+1 item bonus to that triggering Will save');
  });

  it('war blood mutagen (moderate): the release check is Athletics DC 30 and the concentrate check is DC 5 flat', () => {
    // bug 2026-09-15: modes vs print
    const note = item('item-war-blood-mutagen-moderate').note ?? '';
    expect(note).toContain('Athletics check (DC 30)');
    expect(note).toContain('DC 5 flat check');
  });

  it('war blood mutagen (greater): Athletics DC 40', () => {
    // bug 2026-09-15: modes vs print
    const note = item('item-war-blood-mutagen-greater').note ?? '';
    expect(note).toContain('Athletics check (DC 40)');
    expect(note).toContain('DC 5 flat check');
  });

  it('war blood mutagen (major): Athletics DC 50', () => {
    // bug 2026-09-15: modes vs print
    const note = item('item-war-blood-mutagen-major').note ?? '';
    expect(note).toContain('Athletics check (DC 50)');
    expect(note).toContain('DC 5 flat check');
  });
});

describe('toggle-modes.json — auras, forms and the rest', () => {
  it('air gate junction: the kineticist gets their own +10-foot status bonus, land and fly', () => {
    // bug 2026-09-15: modes vs print
    const m = mode('aura-air-gate-junction');
    expect(mods(m)).toEqual([
      { value: 10, type: 'status', target: 'speed' },
      { value: 10, type: 'status', target: 'speed', detail: 'fly' },
    ]);
  });

  it('convocation of earth and moon: 4th-rank Enlarge is +4 and Huge, not the 2nd-rank numbers', () => {
    // bug 2026-09-15: modes vs print
    const m = mode('aura-convocation-of-earth-and-moon');
    expect(modFor(m, 'damage')).toMatchObject({ value: 4, type: 'status' });
    expect(m.note).toContain('Huge');
    expect(m.note).not.toContain('+2 status damage');
  });

  it('a little bird told me: weakness 5 to physical', () => {
    // bug 2026-09-15: modes vs print
    expect(mode('a-little-bird-told-me').weaknesses).toEqual([{ type: 'physical', value: 5 }]);
  });

  it("ancestors' rage: the pill prints the form's duration, not only its frequency", () => {
    // bug 2026-09-15: modes vs print
    expect(mode('ancestors-rage').duration).toBe('up to 1 minute, once per day');
  });

  it('mirrored aegis: the +1 status to AC is unconditional while the toggle is on', () => {
    // bug 2026-09-15: modes vs print
    const m = mode('aura-mirrored-aegis');
    expect(mods(m)).toEqual([{ value: 1, type: 'status', target: 'ac' }]);
  });

  it("victor's wreath: attack and spell attack, neither carrying an appliesWhen that restates the duration", () => {
    // bug 2026-09-15: modes vs print
    const m = mode('aura-victors-wreath');
    expect(mods(m)).toEqual([
      { value: 1, type: 'status', target: 'attack' },
      { value: 1, type: 'status', target: 'spell-attack' },
    ]);
  });

  it('spell attack rolls ARE attack rolls: the eternal blessing aura carries the second modifier too', () => {
    // bug 2026-09-15: modes vs print
    expect(modFor(mode('aura-eternal-blessing'), 'spell-attack')).toMatchObject({ value: 1, type: 'status' });
    expect(modFor(mode('aura-victors-wreath'), 'spell-attack')).toMatchObject({ value: 1, type: 'status' });
  });

  it('wrathful presence: the +3 folds into Strike damage', () => {
    // bug 2026-09-15: modes vs print
    expect(mods(mode('aura-wrathful-presence'))).toEqual([{ value: 3, type: 'status', target: 'damage' }]);
  });

  it('bone swarm: the fly Speed is a GRANT, so the land Speed is not wiped out', () => {
    // bug 2026-09-15: modes vs print
    const m = mode('bone-swarm');
    expect(m.speeds).toEqual({ fly: 40 });
    expect(m.battleForm?.speeds).toBeUndefined();
  });

  it('bone swarm: weakness 5 to area and splash damage', () => {
    // bug 2026-09-15: modes vs print
    expect(mode('bone-swarm').weaknesses).toEqual([
      { type: 'area damage', value: 5 },
      { type: 'splash damage', value: 5 },
    ]);
  });

  it('bone swarm: immune to grabbed, prone and restrained', () => {
    // bug 2026-09-15: modes vs print
    expect(mode('bone-swarm').immunities).toEqual(['grabbed', 'prone', 'restrained']);
  });

  it('bat form: weakness 5 to physical', () => {
    // bug 2026-09-15: modes vs print
    expect(mode('bat-form').weaknesses).toEqual([{ type: 'physical', value: 5 }]);
  });

  it('crawling form: weakness 5 to physical, top-level and not inside battleForm', () => {
    // bug 2026-09-15: modes vs print
    const m = mode('crawling-form');
    expect(m.weaknesses).toEqual([{ type: 'physical', value: 5 }]);
    expect((m.battleForm as unknown as { weaknesses?: unknown }).weaknesses).toBeUndefined();
  });

  it('critter shape: weakness 5 to physical', () => {
    // bug 2026-09-15: modes vs print
    expect(mode('critter-shape').weaknesses).toEqual([{ type: 'physical', value: 5 }]);
  });

  it("bat form: the pill prints pest form's 10 minutes, not only the feat's frequency", () => {
    // bug 2026-09-15: modes vs print
    expect(mode('bat-form').duration).toBe('up to 10 minutes (pest form), once per hour');
  });

  it('dragon transformation: the fly Speed scales to 120 at 18th level', () => {
    // bug 2026-09-15: modes vs print
    expect(mode('dragon-transformation').battleForm?.speeds).toEqual({
      land: 40,
      fly: '100+20*min(1,floor(@actor.level/18))',
    });
  });

  it('form of the bat: weakness 5 to physical', () => {
    // bug 2026-09-15: modes vs print
    expect(mode('form-of-the-bat').weaknesses).toEqual([{ type: 'physical', value: 5 }]);
  });

  it("infused with Belkzen's might: the worked example is no longer off by one", () => {
    // bug 2026-09-15: modes vs print
    const note = mode('infused-with-belkzens-might').note ?? '';
    expect(note).toContain('2 with two or three such feats, 3 with four or five');
    expect(note).not.toContain('so 1 with one or two such feats');
  });

  it('abysium chunk: sickened 1 reaches the DCs, not only the checks', () => {
    // bug 2026-09-15: modes vs print
    const m = mode('item-abysium-chunk');
    for (const target of ['all-checks', 'spell-dc', 'class-dc', 'ac']) {
      expect(modFor(m, target)).toMatchObject({ value: -1, type: 'status' });
    }
  });

  it('abysium ingot: sickened 2 reaches the DCs', () => {
    // bug 2026-09-15: modes vs print
    const m = mode('item-abysium-ingot');
    for (const target of ['all-checks', 'spell-dc', 'class-dc', 'ac']) {
      expect(modFor(m, target)).toMatchObject({ value: -2, type: 'status' });
    }
  });

  it('form of the beloved mother: 5th rank doubles the poison rider die too', () => {
    // bug 2026-09-15: modes vs print
    expect(mode('form-of-the-beloved-mother').battleForm?.strikes?.[0].damage).toBe('4d4+7 piercing plus 2d6 poison');
  });

  it("form of the beloved mother: the pill prints the form's 1 minute", () => {
    // bug 2026-09-15: modes vs print
    expect(mode('form-of-the-beloved-mother').duration).toBe('up to 1 minute, once per day');
  });

  it("form of the bat: the pill prints pest form's 10 minutes", () => {
    // bug 2026-09-15: modes vs print
    expect(mode('form-of-the-bat').duration).toBe('up to 10 minutes, once per hour');
  });

  it('eyes that see eternity: truesight is a 60-ft secret counteract, not magical darkness and not certain', () => {
    // bug 2026-09-15: modes vs print
    const m = mode('eyes-that-see-eternity');
    expect(m.senses?.[0]).toMatchObject({ name: 'see-invisibility', range: 60 });
    expect((m.senses?.[0] as { note?: string }).note).toContain('secret truesight counteract');
    expect(m.note).not.toContain('magical darkness');
  });

  it('eternal blessing ships ONE toggle, not two identical ones', () => {
    // bug 2026-09-15: modes vs print
    expect(toggle['feat-eternal-blessing']).toBeUndefined();
    expect(toggle['aura-eternal-blessing']).toBeTruthy();
  });

  it("giant's stature: Clumsy 1 until you stop raging, applied by the mode", () => {
    // bug 2026-09-15: modes vs print
    const m = mode('giants-stature');
    expect(m.conditions).toEqual([{ id: 'clumsy', value: 1 }]);
    expect(m.note).toContain('Clumsy 1 until you stop raging');
  });

  it('dire form: the Clumsy 1 half of Enlarge is applied, not described', () => {
    // bug 2026-09-15: modes vs print
    expect(mode('dire-form').conditions).toEqual([{ id: 'clumsy', value: 1 }]);
  });

  it('dire growth: the Clumsy 1 half of Enlarge is applied, not described', () => {
    // bug 2026-09-15: modes vs print
    expect(mode('dire-growth').conditions).toEqual([{ id: 'clumsy', value: 1 }]);
  });

  it("azata's grace: the +50 maximum Hit Points is a modifier", () => {
    // bug 2026-09-15: modes vs print
    expect(modFor(mode('item-azatas-grace'), 'max-hp')).toEqual({ target: 'max-hp', type: 'untyped', value: 50 });
  });

  it('blessed tattoo: Protection applies only against evil, and the +3 tier exists', () => {
    // bug 2026-09-15: modes vs print
    const m = mode('item-blessed-tattoo');
    expect(mods(m)).toHaveLength(4);
    expect(mods(m).every((x) => !!x.appliesWhen)).toBe(true);
    expect(mods(m).filter((x) => x.value === 3)).toHaveLength(2);
  });

  it('emotion surge: a Recall Knowledge bonus is a SKILL bonus, not every check', () => {
    // bug 2026-09-15: modes vs print
    const m = mode('item-emotion-surge-dedication');
    expect(mods(m)).toEqual([{ value: 1, type: 'status', target: 'skill', appliesWhen: 'to Recall Knowledge' }]);
  });

  it('stone body mutagen (lesser): all Speeds drop by 10 feet', () => {
    // bug 2026-09-15: modes vs print
    expect(modFor(mode('item-stone-body-mutagen-lesser'), 'speed', 'all')).toEqual({
      value: -10, type: 'untyped', target: 'speed', detail: 'all',
    });
  });

  it('stone body mutagen (moderate): all Speeds drop by 10 feet', () => {
    // bug 2026-09-15: modes vs print
    expect(modFor(mode('item-stone-body-mutagen-moderate'), 'speed', 'all')).toEqual({
      value: -10, type: 'untyped', target: 'speed', detail: 'all',
    });
  });

  it('soaring wings (major): lasts until Dismissed, with no per-day limit', () => {
    // bug 2026-09-15: modes vs print
    const m = mode('item-soaring-wings-major');
    expect(m.duration).toBe('until you Dismiss the activation');
    expect(m.note).toContain('any number of times');
  });

  it('living statue: a permanent relic passive is not switched off by rest', () => {
    // bug 2026-09-15: modes vs print
    expect(mode('item-living-statue').survivesRest).toBe(true);
  });

  it('saurian spike (major): an affixed spellheart survives the night', () => {
    // bug 2026-09-15: modes vs print
    expect(mode('item-saurian-spike-major').survivesRest).toBe(true);
  });

  it('spiny lodestone: an affixed spellheart survives the night', () => {
    // bug 2026-09-15: modes vs print
    expect(mode('item-spiny-lodestone').survivesRest).toBe(true);
  });

  it('spiny lodestone (greater): an affixed spellheart survives the night', () => {
    // bug 2026-09-15: modes vs print
    expect(mode('item-spiny-lodestone-greater').survivesRest).toBe(true);
  });

  it('zetogeki hide armor: the -10 ft to all Speeds is applied, not left to the player', () => {
    // bug 2026-09-15: modes vs print
    const m = mode('item-zetogeki-hide-armor');
    expect(modFor(m, 'speed', 'all')).toEqual({ value: -10, type: 'untyped', target: 'speed', detail: 'all' });
    expect(m.note).not.toContain("the app can't apply that yet");
  });

  it("klingegeist: the blade's AC 18 + level replaces your own, and the fly Speed moved inside the form", () => {
    // bug 2026-09-15: modes vs print
    const m = mode('klingegeist');
    expect(m.battleForm).toEqual({ ac: '18+@actor.level', speeds: { fly: 30 } });
    expect(m.speeds).toBeUndefined();
    expect(m.exclusiveGroup).toBe('battle-form');
  });

  it('klingegeist: the duration is the printed 10 minutes, not a restatement of itself', () => {
    // bug 2026-09-15: modes vs print
    expect(mode('klingegeist').duration).toBe('10 minutes or until you Dismiss it');
  });

  it('the mutagenist field vial has ONE toggle, gated on the 11th-level advanced vials', () => {
    // bug 2026-09-15: modes vs print
    expect(toggle['mode-mutagenist-field-vial']).toBeUndefined();
    const kept = mode('field-vial-mutagenist');
    expect(kept.feats).toEqual(['advanced-vials-mutagenist']);
    expect(kept.duration).toBe('1 minute');
  });

  it('rat form: weakness 5 to physical', () => {
    // bug 2026-09-15: modes vs print
    expect(mode('rat-form').weaknesses).toEqual([{ type: 'physical', value: 5 }]);
  });

  it('rat form: the pill prints the 10-minute duration', () => {
    // bug 2026-09-15: modes vs print
    expect(mode('rat-form').duration).toBe('10 minutes, or until you Dismiss it');
  });

  /* "Ignore your armor's check penalty and Speed reduction" is printed on every ac-bearing battle
   * form. Honouring it is a deriveSpeeds / deriveArmorCheckPenalty guard, not a record field — the
   * engine lane built it, and test/bug-modes-engine.test.ts §2 moves the numbers. What this file owns
   * is the DATA the guard keys on: the forms that print the sentence are exactly the ones stating an
   * AC, and a form stating none (a werecreature's Change Shape) must keep paying for its armour. */
  it("pest/elemental/cosmic forms state the AC the armour guard keys on, and a Speed-only shape does not", () => {
    // bug 2026-09-15: modes vs print
    for (const id of ['critter-shape', 'storm-form', 'transcend-the-azimuth-moon', 'transcend-the-azimuth-sun']) {
      expect(`${id}: ${typeof mode(id).battleForm?.ac}`).toBe(`${id}: string`);
    }
    expect(mode('were-werewolf-animal').battleForm?.ac, 'a Change Shape states Speeds and no AC').toBeUndefined();
  });

  it('segmented frame: the +2 Stealth is scoped to concealing the innovation, not to Hide and Sneak', () => {
    // bug 2026-09-15: modes vs print
    const mod = modFor(mode('segmented-frame-collapsed'), 'skill', 'stealth');
    expect(mod?.appliesWhen).toContain('conceal the innovation');
  });

  it('warped by rage: Huge from 4th-rank Enlarge, and the clumsy 1 penalty is real', () => {
    // bug 2026-09-15: modes vs print
    /* The −1 status penalty to the Dex modifier was this record's hand-rolled stand-in for Clumsy 1,
     * written when ModeDef had no `conditions`. Keeping BOTH would charge the penalty twice: the mode
     * modifier lands on the attribute modifier (derive.ts abilityModWithModes) while the condition
     * lands on each check and DC (conditions.ts conditionTypedMods), two different layers that never
     * pool. The condition is the printed one, so it replaces the stand-in. */
    const m = mode('warped-by-rage');
    expect(m.battleForm?.size).toBe('Huge');
    expect(m.conditions).toEqual([{ id: 'clumsy', value: 1 }]);
    expect(modFor(m, 'ability', 'dex'), 'the hand-rolled Dex penalty would double the condition').toBeUndefined();
  });

  it('scouring spark: the unarmed 1d6 fire rider rides the Strikes', () => {
    // bug 2026-09-15: modes vs print
    const m = mode('scouring-spark');
    expect(m.strikeDamage).toEqual([
      { type: 'fire', appliesTo: 'unarmed', dice: { n: 1, die: 'd6' }, note: 'Scouring Spark' },
    ]);
    expect(m.note).not.toContain("aren't applied to your Strikes yet");
  });

  it('the tyrant falls: melee weapons gain reach and an extra 2d6', () => {
    // bug 2026-09-15: modes vs print
    const m = mode('the-tyrant-falls');
    expect(m.weaponTraits).toEqual({ match: { melee: true }, add: ['reach'] });
    expect(m.strikeDamage).toEqual([
      { type: 'vitality or void', appliesTo: 'melee', dice: { n: 2, die: 'd6' }, note: 'The Tyrant Falls!' },
    ]);
  });

  it("the tyrant falls: the all-damage resistance uses the key the rest of the corpus uses ('all')", () => {
    // bug 2026-09-15: modes vs print
    expect(mode('the-tyrant-falls').resistances).toEqual([{ type: 'all', value: 'floor(@actor.level/2)' }]);
  });

  it('shore gift: walking on two legs really does take the merfolk swim Speed away', () => {
    // bug 2026-09-15: modes vs print
    const m = mode('shore-gift');
    expect(m.battleForm).toEqual({ speeds: { land: 25 } });
    expect(m.speeds).toBeUndefined();
  });

  it('winged: the printed duration is 5 minutes', () => {
    // bug 2026-09-15: modes vs print
    expect(mode('item-winged').duration).toBe('5 minutes, or until you Dismiss it');
  });

  it("wyrm's flight: 10 minutes, and unlimited from 17th level", () => {
    // bug 2026-09-15: modes vs print
    const m = mode('item-wyrms-flight');
    expect(m.duration).toBe('10 minutes or until you Dismiss it (unlimited at 17th level)');
    expect(m.note).toContain('17th level');
  });

  it("storm form: the pill prints the spell's 1 minute, not the feat's frequency alone", () => {
    // bug 2026-09-15: modes vs print
    expect(mode('storm-form').duration).toBe('1 minute or until you Dismiss it (once per day)');
  });

  it('transcend the azimuth (moon): 1 minute, once per day', () => {
    // bug 2026-09-15: modes vs print
    expect(mode('transcend-the-azimuth-moon').duration).toBe('up to 1 minute or until you Dismiss it, once per day');
  });

  it('transcend the azimuth (sun): 1 minute, once per day', () => {
    // bug 2026-09-15: modes vs print
    expect(mode('transcend-the-azimuth-sun').duration).toBe('up to 1 minute or until you Dismiss it, once per day');
  });

  it('raging stories: the base +2 fire rides melee Strikes instead of sitting in a conditional modifier', () => {
    // bug 2026-09-15: modes vs print
    const m = mode('raging-stories');
    expect(mods(m)).toEqual([]);
    expect(m.strikeDamage).toEqual([
      { type: 'fire', appliesTo: 'melee', flat: 2, note: 'Raging Stories (4 if you are a master in Religion, 6 if legendary)' },
    ]);
  });

  it('harrow chosen (unmatched): temporary Hit Points are TWICE your level, for 1 minute', () => {
    // bug 2026-09-15: modes vs print
    const m = mode('harrow-chosen-unmatched');
    expect(m.note).toContain('twice your level');
    expect(m.note).not.toContain('2 + half your level');
    expect(m.duration).toBe('1 minute');
  });

  it('harrow chosen (partial match): the pill prints the 1 minute', () => {
    // bug 2026-09-15: modes vs print
    expect(mode('harrow-chosen-partial-match').duration).toBe('1 minute');
  });

  it('energetic meltdown: a daily-preparations backlash is cleared by the rest that ends it', () => {
    // bug 2026-09-15: modes vs print
    expect(mode('energetic-meltdown').survivesRest).toBeUndefined();
  });

  it("hunter's brooch: the deadly d12 rider is narrowed to the ONE weapon you touched to the symbol", () => {
    // bug 2026-09-15: modes vs print
    /* Was an it.todo: the fix needed ItemDesignation 'steadying-hand' and a control to set it, both of
     * which the engine lane has now built (applyWeaponRiders honours `match.designated`). With an empty
     * `match` the rider landed on every equipped weapon and the note had to apologise for it. */
    const m = mode('item-hunters-brooch');
    expect(m.weaponTraits).toEqual({ match: { designated: 'steadying-hand' }, add: ['deadly-d12'] });
    expect(m.note).not.toContain('every equipped weapon');
  });

  it('shore gift: a polymorph form is mutually exclusive with every other one', () => {
    // bug 2026-09-15: modes vs print
    /* feat-5354 carries the `polymorph` trait, and two polymorph effects at once is not a creature any
     * book prints — `activeBattleForm` takes the first and the rest vanish silently. Every other
     * battleForm record already says so; this one shipped without the group, which is the state
     * test/battle-form.test.ts fails on. That leg reads public/core.json, so it goes green when the
     * seed is regenerated; this one proves the SOURCE. */
    const m = mode('shore-gift');
    expect(m.battleForm?.speeds).toEqual({ land: 25 });
    expect(m.exclusiveGroup).toBe('battle-form');
  });
});

/*
 * CONDITIONS — the printed "you are clumsy 1 / encumbered / enfeebled N" half of a mode.
 *
 * Until the engine lane added `ModeDef.conditions` these sentences had no carrier at all, so each one
 * shipped as a note asking the player to open the Conditions panel and do the app's arithmetic by
 * hand. One leg per record, because which record gets which value is the whole finding: a clumsy 1
 * authored on a record whose text prints clumsy 2 is a wrong number, not a missing one.
 */
describe('modes that APPLY the condition their text prints', () => {
  const clumsy1 = (m: ModeDef) => expect(m.conditions).toEqual([{ id: 'clumsy', value: 1 }]);

  it('apricot of bestial might: "You become Clumsy 1"', () => {
    // bug 2026-09-15: modes vs print
    const m = item('item-apricot-of-bestial-might');
    clumsy1(m);
    expect(m.note).not.toContain('apply as a condition');
  });

  it('hydra mutagen: "You are Clumsy 1 for 10 minutes"', () => {
    // bug 2026-09-15: modes vs print
    const m = item('item-hydra-mutagen');
    clumsy1(m);
    expect(m.note).not.toContain('apply as a condition');
  });

  it('giant catch pole: "you are Clumsy 1 while wielding it"', () => {
    // bug 2026-09-15: modes vs print
    const m = mode('item-giant-catch-pole');
    clumsy1(m);
    expect(m.note).not.toContain('apply as a condition');
  });

  it('dinosaur boots: Enlarge makes the wearer clumsy 1', () => {
    // bug 2026-09-15: modes vs print
    // The boots print "the effects of Enlarge"; enlarge (spell-1502's sibling) prints "The creature is
    // Clumsy 1", at 2nd rank and at the 4th-rank heightening alike — so both grades take the same 1.
    const m = item('item-dinosaur-boots');
    clumsy1(m);
    expect(m.note).not.toContain('apply the condition');
  });

  it('dinosaur boots (greater): 4th-rank Enlarge is still clumsy 1', () => {
    // bug 2026-09-15: modes vs print
    clumsy1(item('item-dinosaur-boots-greater'));
  });

  it('convocation of earth and moon: the 4th-rank Enlarge half is clumsy 1', () => {
    // bug 2026-09-15: modes vs print
    const m = mode('aura-convocation-of-earth-and-moon');
    clumsy1(m);
    expect(m.note).not.toContain('apply it as a condition');
  });

  it("curse of the sky's call: enfeebled equals the cursebound value, rung by rung", () => {
    // bug 2026-09-15: modes vs print
    /* Was an it.todo. mystery-15: "you are enfeebled with a value equal to your cursebound value" —
     * four rungs, four values, and authoring 1 on all four would be the failure this leg exists for.
     * These four records live ONLY as overlay create rows, so the `conditions` field is an overlay row
     * of its own (scripts/apply-parity-fixes.mjs), applied after the create. */
    for (const n of [1, 2, 3, 4]) {
      const id = `curse-of-the-skys-call-${n}`;
      expect(`rung ${n}: ${JSON.stringify(overlayField(id, 'conditions'))}`).toBe(
        `rung ${n}: ${JSON.stringify([{ id: 'enfeebled', value: n }])}`,
      );
      expect(overlayMode(id).note).toContain(`enfeebled ${n}`);
    }
  });
});

describe('effect-backfill.json — the modes with no seed-file row', () => {
  it('scar of the survivor: the Fortitude bonus no longer hides behind an appliesWhen that restates the toggle', () => {
    // bug 2026-09-15: modes vs print
    const m = overlayMode('scar-of-the-survivor');
    expect(mods(m)).toEqual([{ value: 1, type: 'status', target: 'save', detail: 'fortitude' }]);
    expect(m.note).not.toContain('raise it by hand');
  });

  it('scar of the survivor: the Diehard half raises the death threshold', () => {
    // bug 2026-09-15: modes vs print
    expect(overlayMode('scar-of-the-survivor').dyingThresholdBonus).toBe(1);
  });

  it('soul well: living creatures in the well die at dying 5', () => {
    // bug 2026-09-15: modes vs print
    const m = overlayMode('soul-well');
    expect(m.dyingThresholdBonus).toBe(1);
    expect(m.note).not.toContain('Raise the death threshold by hand');
  });
});
