/*
 * Class proficiency advancement (PF2e Player Core).
 *
 * PF2e raises a class's proficiencies (saves, perception, weapons, armor, class
 * DC, spellcasting) to expert/master/legendary at fixed levels. That progression
 * is NOT in the Foundry compendium data — the class JSON carries only level-1
 * ranks, and the bumps are applied by the Foundry *system code* keyed off feature
 * slugs. So it is hand-authored here, anchored to the data-sourced feature levels
 * and verified against the published class tables / Foundry feature descriptions.
 *
 * buildCharacter applies, for each entry with level <= the character's level, the
 * higher of the base rank and the entry rank to that track (it never lowers a rank).
 *
 * Weapon advancement is expressed per category (unarmed/simple/martial/advanced);
 * advanced weapons lag one rank for fighters.
 *
 * Cleric is doctrine-dependent: the `cleric` key is the Cloistered Cleric default
 * (divine spell expert@7/master@15/legendary@19); `warpriest` is a subclass-keyed
 * override (armor + martial weapons, Fort master@15, spell capped at master@19).
 * buildCharacter looks up CLASS_ADVANCEMENT[subclassId] first, then [classId].
 */
import type { AdvancementEntry } from './types';

export const CLASS_ADVANCEMENT: Record<string, AdvancementEntry[]> = {
  bard: [
    { level: 3, track: 'reflex', rank: 'expert', source: 'reflex-expertise' },
    { level: 7, track: 'spellcasting', rank: 'expert', source: 'expert-spellcaster' },
    { level: 9, track: 'fortitude', rank: 'expert', source: 'fortitude-expertise' },
    { level: 9, track: 'will', rank: 'master', source: 'performers-heart' },
    { level: 11, track: 'perception', rank: 'master', source: 'perception-mastery' },
    { level: 17, track: 'will', rank: 'legendary', source: 'greater-performers-heart' },
    { level: 11, track: 'unarmed', rank: 'expert', source: 'bard-weapon-expertise' },
    { level: 11, track: 'simple', rank: 'expert', source: 'bard-weapon-expertise' },
    { level: 11, track: 'martial', rank: 'expert', source: 'bard-weapon-expertise' },
    { level: 13, track: 'unarmored', rank: 'expert', source: 'light-armor-expertise' },
    { level: 13, track: 'light', rank: 'expert', source: 'light-armor-expertise' },
    { level: 15, track: 'spellcasting', rank: 'master', source: 'master-spellcaster' },
    { level: 19, track: 'spellcasting', rank: 'legendary', source: 'legendary-spellcaster' },
  ],
  // Cloistered Cleric doctrine assumed (see header).
  cleric: [
    { level: 3, track: 'fortitude', rank: 'expert', source: 'second-doctrine (cloistered)' },
    { level: 5, track: 'perception', rank: 'expert', source: 'perception-expertise' },
    { level: 7, track: 'spellcasting', rank: 'expert', source: 'third-doctrine (cloistered)' },
    { level: 9, track: 'will', rank: 'master', source: 'resolute-faith' },
    { level: 11, track: 'reflex', rank: 'expert', source: 'reflex-expertise' },
    { level: 11, track: 'unarmed', rank: 'expert', source: 'fourth-doctrine (cloistered)' },
    { level: 11, track: 'simple', rank: 'expert', source: 'fourth-doctrine (cloistered)' },
    { level: 13, track: 'unarmored', rank: 'expert', source: 'divine-defense' },
    { level: 15, track: 'spellcasting', rank: 'master', source: 'fifth-doctrine (cloistered)' },
    { level: 19, track: 'spellcasting', rank: 'legendary', source: 'final-doctrine (cloistered)' },
  ],
  // Warpriest cleric doctrine (subclass-keyed override of the cloistered default).
  warpriest: [
    { level: 1, track: 'light', rank: 'trained', source: 'first-doctrine (warpriest)' },
    { level: 1, track: 'medium', rank: 'trained', source: 'first-doctrine (warpriest)' },
    { level: 1, track: 'fortitude', rank: 'expert', source: 'first-doctrine (warpriest)' },
    { level: 3, track: 'martial', rank: 'trained', source: 'second-doctrine (warpriest)' },
    { level: 5, track: 'perception', rank: 'expert', source: 'perception-expertise' },
    { level: 7, track: 'unarmed', rank: 'expert', source: 'third-doctrine (warpriest)' },
    { level: 7, track: 'simple', rank: 'expert', source: 'third-doctrine (warpriest)' },
    { level: 7, track: 'martial', rank: 'expert', source: 'third-doctrine (warpriest)' },
    { level: 9, track: 'will', rank: 'master', source: 'resolute-faith' },
    { level: 11, track: 'reflex', rank: 'expert', source: 'reflex-expertise' },
    { level: 11, track: 'spellcasting', rank: 'expert', source: 'fourth-doctrine (warpriest)' },
    { level: 13, track: 'unarmored', rank: 'expert', source: 'divine-defense' },
    { level: 13, track: 'light', rank: 'expert', source: 'first-doctrine (warpriest)' },
    { level: 13, track: 'medium', rank: 'expert', source: 'first-doctrine (warpriest)' },
    { level: 15, track: 'fortitude', rank: 'master', source: 'fifth-doctrine (warpriest)' },
    { level: 19, track: 'spellcasting', rank: 'master', source: 'final-doctrine (warpriest)' },
  ],
  // Battle Creed cleric doctrine (Battle Harbinger) — replaces the cloistered ladder entirely.
  // Combat-focused: armor + martial weapons, a creed proficiency ladder, NO resolute-faith
  // will-master@9 and NO spellcasting master/legendary (it loses Miraculous Spell + caps casting).
  'battle-creed': [
    // Initial Creed (1): trained light & medium armor + martial weapons; expert Fortitude.
    { level: 1, track: 'light', rank: 'trained', source: 'initial-creed' },
    { level: 1, track: 'medium', rank: 'trained', source: 'initial-creed' },
    { level: 1, track: 'martial', rank: 'trained', source: 'initial-creed' },
    { level: 1, track: 'fortitude', rank: 'expert', source: 'initial-creed' },
    { level: 5, track: 'perception', rank: 'expert', source: 'perception-expertise' },
    // Lesser Creed (5): expert simple/martial/unarmed weapons; class DC expert.
    { level: 5, track: 'simple', rank: 'expert', source: 'lesser-creed' },
    { level: 5, track: 'martial', rank: 'expert', source: 'lesser-creed' },
    { level: 5, track: 'unarmed', rank: 'expert', source: 'lesser-creed' },
    { level: 5, track: 'classDc', rank: 'expert', source: 'lesser-creed' },
    { level: 11, track: 'reflex', rank: 'expert', source: 'reflex-expertise' },
    // Greater Creed (11): spell attack + spell DC expert (casting never advances past expert).
    { level: 11, track: 'spellcasting', rank: 'expert', source: 'greater-creed' },
    // Divine Defense (13): expert light & medium armor + unarmored.
    { level: 13, track: 'unarmored', rank: 'expert', source: 'divine-defense' },
    { level: 13, track: 'light', rank: 'expert', source: 'divine-defense' },
    { level: 13, track: 'medium', rank: 'expert', source: 'divine-defense' },
    // Major Creed (13): Fortitude master.
    { level: 13, track: 'fortitude', rank: 'master', source: 'major-creed' },
    // True Creed (15): class DC + Will master.
    { level: 15, track: 'classDc', rank: 'master', source: 'true-creed' },
    { level: 15, track: 'will', rank: 'master', source: 'true-creed' },
    // Final Creed (19): light/medium/unarmored defense master; class DC legendary.
    { level: 19, track: 'light', rank: 'master', source: 'final-creed' },
    { level: 19, track: 'medium', rank: 'master', source: 'final-creed' },
    { level: 19, track: 'unarmored', rank: 'master', source: 'final-creed' },
    { level: 19, track: 'classDc', rank: 'legendary', source: 'final-creed' },
  ],
  druid: [
    { level: 3, track: 'perception', rank: 'expert', source: 'perception-expertise' },
    { level: 3, track: 'fortitude', rank: 'expert', source: 'fortitude-expertise' },
    { level: 5, track: 'reflex', rank: 'expert', source: 'reflex-expertise' },
    { level: 7, track: 'spellcasting', rank: 'expert', source: 'expert-spellcaster' },
    { level: 11, track: 'will', rank: 'master', source: 'wild-willpower' },
    { level: 11, track: 'unarmed', rank: 'expert', source: 'weapon-expertise' },
    { level: 11, track: 'simple', rank: 'expert', source: 'weapon-expertise' },
    { level: 13, track: 'unarmored', rank: 'expert', source: 'medium-armor-expertise' },
    { level: 13, track: 'light', rank: 'expert', source: 'medium-armor-expertise' },
    { level: 13, track: 'medium', rank: 'expert', source: 'medium-armor-expertise' },
    { level: 15, track: 'spellcasting', rank: 'master', source: 'master-spellcaster' },
    { level: 19, track: 'spellcasting', rank: 'legendary', source: 'legendary-spellcaster' },
  ],
  fighter: [
    { level: 3, track: 'will', rank: 'expert', source: 'bravery' },
    // Fighter Weapon Mastery (L5) and Weapon Legend (L13) raise proficiency for the simple/martial/
    // unarmed weapons in ONE CHOSEN weapon GROUP (master@5 / legendary@13), not for ALL weapons — that
    // group bump is applied in buildCharacter via proficiencies.weaponGroups keyed off the player's
    // fighterWeaponGroup pick. Only the GENERAL, all-weapon clause of Weapon Legend belongs in this
    // table: at L13 all simple/martial/unarmed become master and all advanced become expert. Before
    // L13 a fighter is merely expert in simple/martial/unarmed (class chassis) outside their group.
    { level: 7, track: 'perception', rank: 'master', source: 'battlefield-surveyor' },
    { level: 9, track: 'fortitude', rank: 'master', source: 'battle-hardened' },
    { level: 11, track: 'unarmored', rank: 'expert', source: 'armor-expertise' },
    { level: 11, track: 'light', rank: 'expert', source: 'armor-expertise' },
    { level: 11, track: 'medium', rank: 'expert', source: 'armor-expertise' },
    { level: 11, track: 'heavy', rank: 'expert', source: 'armor-expertise' },
    { level: 11, track: 'classDc', rank: 'expert', source: 'fighter-expertise' },
    { level: 13, track: 'unarmed', rank: 'master', source: 'weapon-legend (general)' },
    { level: 13, track: 'simple', rank: 'master', source: 'weapon-legend (general)' },
    { level: 13, track: 'martial', rank: 'master', source: 'weapon-legend (general)' },
    { level: 13, track: 'advanced', rank: 'expert', source: 'weapon-legend (general)' },
    { level: 15, track: 'reflex', rank: 'master', source: 'tempered-reflexes' },
    { level: 17, track: 'unarmored', rank: 'master', source: 'armor-mastery' },
    { level: 17, track: 'light', rank: 'master', source: 'armor-mastery' },
    { level: 17, track: 'medium', rank: 'master', source: 'armor-mastery' },
    { level: 17, track: 'heavy', rank: 'master', source: 'armor-mastery' },
    { level: 19, track: 'classDc', rank: 'master', source: 'versatile-legend' },
  ],
  ranger: [
    { level: 3, track: 'will', rank: 'expert', source: 'will-expertise' },
    { level: 5, track: 'unarmed', rank: 'expert', source: 'ranger-weapon-expertise' },
    { level: 5, track: 'simple', rank: 'expert', source: 'ranger-weapon-expertise' },
    { level: 5, track: 'martial', rank: 'expert', source: 'ranger-weapon-expertise' },
    { level: 7, track: 'reflex', rank: 'master', source: 'natural-reflexes' },
    { level: 7, track: 'perception', rank: 'master', source: 'perception-mastery' },
    { level: 9, track: 'classDc', rank: 'expert', source: 'ranger-expertise' },
    { level: 11, track: 'fortitude', rank: 'master', source: 'wardens-endurance' },
    { level: 11, track: 'unarmored', rank: 'expert', source: 'medium-armor-expertise' },
    { level: 11, track: 'light', rank: 'expert', source: 'medium-armor-expertise' },
    { level: 11, track: 'medium', rank: 'expert', source: 'medium-armor-expertise' },
    { level: 13, track: 'unarmed', rank: 'master', source: 'weapon-mastery' },
    { level: 13, track: 'simple', rank: 'master', source: 'weapon-mastery' },
    { level: 13, track: 'martial', rank: 'master', source: 'weapon-mastery' },
    { level: 15, track: 'reflex', rank: 'legendary', source: 'greater-natural-reflexes' },
    { level: 15, track: 'perception', rank: 'legendary', source: 'perception-legend' },
    { level: 17, track: 'classDc', rank: 'master', source: 'masterful-hunter' },
    { level: 19, track: 'unarmored', rank: 'master', source: 'medium-armor-mastery' },
    { level: 19, track: 'light', rank: 'master', source: 'medium-armor-mastery' },
    { level: 19, track: 'medium', rank: 'master', source: 'medium-armor-mastery' },
  ],
  rogue: [
    { level: 5, track: 'unarmed', rank: 'expert', source: 'weapon-tricks' },
    { level: 5, track: 'simple', rank: 'expert', source: 'weapon-tricks' },
    { level: 5, track: 'martial', rank: 'expert', source: 'weapon-tricks' },
    { level: 7, track: 'perception', rank: 'master', source: 'perception-mastery' },
    { level: 7, track: 'reflex', rank: 'master', source: 'evasive-reflexes' },
    { level: 9, track: 'fortitude', rank: 'expert', source: 'rogue-resilience' },
    { level: 11, track: 'classDc', rank: 'expert', source: 'rogue-expertise' },
    { level: 13, track: 'perception', rank: 'legendary', source: 'perception-legend' },
    { level: 13, track: 'reflex', rank: 'legendary', source: 'greater-rogue-reflexes' },
    { level: 13, track: 'unarmed', rank: 'master', source: 'master-tricks' },
    { level: 13, track: 'simple', rank: 'master', source: 'master-tricks' },
    { level: 13, track: 'martial', rank: 'master', source: 'master-tricks' },
    { level: 13, track: 'unarmored', rank: 'expert', source: 'light-armor-expertise' },
    { level: 13, track: 'light', rank: 'expert', source: 'light-armor-expertise' },
    { level: 17, track: 'will', rank: 'master', source: 'agile-mind' },
    { level: 19, track: 'classDc', rank: 'master', source: 'master-strike' },
    { level: 19, track: 'unarmored', rank: 'master', source: 'light-armor-mastery' },
    { level: 19, track: 'light', rank: 'master', source: 'light-armor-mastery' },
  ],
  witch: [
    { level: 5, track: 'fortitude', rank: 'expert', source: 'magical-fortitude' },
    { level: 7, track: 'spellcasting', rank: 'expert', source: 'expert-spellcaster' },
    { level: 9, track: 'reflex', rank: 'expert', source: 'reflex-expertise' },
    { level: 11, track: 'perception', rank: 'expert', source: 'perception-expertise' },
    { level: 11, track: 'unarmed', rank: 'expert', source: 'weapon-expertise' },
    { level: 11, track: 'simple', rank: 'expert', source: 'weapon-expertise' },
    { level: 13, track: 'unarmored', rank: 'expert', source: 'defensive-robes' },
    { level: 15, track: 'spellcasting', rank: 'master', source: 'master-spellcaster' },
    { level: 17, track: 'will', rank: 'master', source: 'will-of-the-pupil' },
    { level: 19, track: 'spellcasting', rank: 'legendary', source: 'legendary-spellcaster' },
  ],
  wizard: [
    { level: 5, track: 'reflex', rank: 'expert', source: 'reflex-expertise' },
    { level: 7, track: 'spellcasting', rank: 'expert', source: 'expert-spellcaster' },
    { level: 9, track: 'fortitude', rank: 'expert', source: 'magical-fortitude' },
    { level: 11, track: 'perception', rank: 'expert', source: 'perception-expertise' },
    { level: 11, track: 'unarmed', rank: 'expert', source: 'weapon-expertise' },
    { level: 11, track: 'simple', rank: 'expert', source: 'weapon-expertise' },
    { level: 13, track: 'unarmored', rank: 'expert', source: 'defensive-robes' },
    { level: 15, track: 'spellcasting', rank: 'master', source: 'master-spellcaster' },
    { level: 17, track: 'will', rank: 'master', source: 'prodigious-will' },
    { level: 19, track: 'spellcasting', rank: 'legendary', source: 'legendary-spellcaster' },
  ],
  alchemist: [
    { level: 7, track: 'will', rank: 'expert', source: 'will-expertise' },
    { level: 7, track: 'unarmed', rank: 'expert', source: 'alchemical-weapon-expertise' },
    { level: 7, track: 'simple', rank: 'expert', source: 'alchemical-weapon-expertise' },
    { level: 7, track: 'bomb', rank: 'expert', source: 'alchemical-weapon-expertise' },
    { level: 9, track: 'perception', rank: 'expert', source: 'perception-expertise' },
    { level: 9, track: 'classDc', rank: 'expert', source: 'alchemical-expertise' },
    { level: 11, track: 'fortitude', rank: 'master', source: 'chemical-hardiness' },
    { level: 13, track: 'unarmored', rank: 'expert', source: 'medium-armor-expertise' },
    { level: 13, track: 'light', rank: 'expert', source: 'medium-armor-expertise' },
    { level: 13, track: 'medium', rank: 'expert', source: 'medium-armor-expertise' },
    { level: 15, track: 'reflex', rank: 'master', source: 'explosion-dodger' },
    { level: 15, track: 'unarmed', rank: 'master', source: 'alchemical-weapon-mastery' },
    { level: 15, track: 'simple', rank: 'master', source: 'alchemical-weapon-mastery' },
    { level: 15, track: 'bomb', rank: 'master', source: 'alchemical-weapon-mastery' },
    { level: 17, track: 'classDc', rank: 'master', source: 'alchemical-mastery' },
    { level: 19, track: 'unarmored', rank: 'master', source: 'medium-armor-mastery' },
    { level: 19, track: 'light', rank: 'master', source: 'medium-armor-mastery' },
    { level: 19, track: 'medium', rank: 'master', source: 'medium-armor-mastery' },
  ],
  animist: [
    { level: 3, track: 'fortitude', rank: 'expert', source: 'fortitude-expertise' },
    { level: 7, track: 'spellcasting', rank: 'expert', source: 'expert-spellcaster' },
    { level: 9, track: 'perception', rank: 'expert', source: 'perception-expertise' },
    { level: 11, track: 'reflex', rank: 'expert', source: 'expert-protections' },
    { level: 11, track: 'unarmed', rank: 'expert', source: 'simple-weapon-expertise' },
    { level: 11, track: 'simple', rank: 'expert', source: 'simple-weapon-expertise' },
    { level: 11, track: 'unarmored', rank: 'expert', source: 'expert-protections' },
    { level: 11, track: 'light', rank: 'expert', source: 'expert-protections' },
    { level: 11, track: 'medium', rank: 'expert', source: 'expert-protections' },
    { level: 13, track: 'will', rank: 'master', source: 'master-of-mind-and-spirit' },
    { level: 15, track: 'spellcasting', rank: 'master', source: 'master-spellcaster' },
    { level: 19, track: 'spellcasting', rank: 'legendary', source: 'legendary-spellcaster' },
  ],
  barbarian: [
    { level: 5, track: 'unarmed', rank: 'expert', source: 'brutality' },
    { level: 5, track: 'simple', rank: 'expert', source: 'brutality' },
    { level: 5, track: 'martial', rank: 'expert', source: 'brutality' },
    { level: 7, track: 'fortitude', rank: 'master', source: 'juggernaut' },
    { level: 9, track: 'reflex', rank: 'expert', source: 'reflex-expertise' },
    { level: 11, track: 'classDc', rank: 'expert', source: 'mighty-rage' },
    { level: 13, track: 'fortitude', rank: 'legendary', source: 'greater-juggernaut' },
    { level: 13, track: 'unarmed', rank: 'master', source: 'weapon-mastery' },
    { level: 13, track: 'simple', rank: 'master', source: 'weapon-mastery' },
    { level: 13, track: 'martial', rank: 'master', source: 'weapon-mastery' },
    { level: 13, track: 'unarmored', rank: 'expert', source: 'medium-armor-expertise' },
    { level: 13, track: 'light', rank: 'expert', source: 'medium-armor-expertise' },
    { level: 13, track: 'medium', rank: 'expert', source: 'medium-armor-expertise' },
    { level: 15, track: 'will', rank: 'master', source: 'indomitable-will' },
    { level: 17, track: 'perception', rank: 'master', source: 'perception-mastery' },
    { level: 19, track: 'classDc', rank: 'master', source: 'devastator' },
    { level: 19, track: 'unarmored', rank: 'master', source: 'armor-mastery' },
    { level: 19, track: 'light', rank: 'master', source: 'armor-mastery' },
    { level: 19, track: 'medium', rank: 'master', source: 'armor-mastery' },
  ],
  champion: [
    { level: 5, track: 'unarmed', rank: 'expert', source: 'weapon-expertise' },
    { level: 5, track: 'simple', rank: 'expert', source: 'weapon-expertise' },
    { level: 5, track: 'martial', rank: 'expert', source: 'weapon-expertise' },
    { level: 7, track: 'unarmored', rank: 'expert', source: 'armor-expertise' },
    { level: 7, track: 'light', rank: 'expert', source: 'armor-expertise' },
    { level: 7, track: 'medium', rank: 'expert', source: 'armor-expertise' },
    { level: 7, track: 'heavy', rank: 'expert', source: 'armor-expertise' },
    { level: 9, track: 'fortitude', rank: 'master', source: 'sacred-body' },
    { level: 9, track: 'reflex', rank: 'expert', source: 'reflex-expertise' },
    { level: 9, track: 'classDc', rank: 'expert', source: 'champion-expertise' },
    { level: 9, track: 'spellcasting', rank: 'expert', source: 'champion-expertise' },
    { level: 11, track: 'perception', rank: 'expert', source: 'perception-expertise' },
    { level: 11, track: 'will', rank: 'master', source: 'divine-will' },
    { level: 13, track: 'unarmed', rank: 'master', source: 'weapon-mastery' },
    { level: 13, track: 'simple', rank: 'master', source: 'weapon-mastery' },
    { level: 13, track: 'martial', rank: 'master', source: 'weapon-mastery' },
    { level: 13, track: 'unarmored', rank: 'master', source: 'armor-mastery' },
    { level: 13, track: 'light', rank: 'master', source: 'armor-mastery' },
    { level: 13, track: 'medium', rank: 'master', source: 'armor-mastery' },
    { level: 13, track: 'heavy', rank: 'master', source: 'armor-mastery' },
    { level: 17, track: 'classDc', rank: 'master', source: 'champion-mastery' },
    { level: 17, track: 'spellcasting', rank: 'master', source: 'champion-mastery' },
    { level: 17, track: 'unarmored', rank: 'legendary', source: 'legendary-armor' },
    { level: 17, track: 'light', rank: 'legendary', source: 'legendary-armor' },
    { level: 17, track: 'medium', rank: 'legendary', source: 'legendary-armor' },
    { level: 17, track: 'heavy', rank: 'legendary', source: 'legendary-armor' },
  ],
  commander: [
    { level: 5, track: 'unarmed', rank: 'expert', source: 'military-expertise' },
    { level: 5, track: 'simple', rank: 'expert', source: 'military-expertise' },
    { level: 5, track: 'martial', rank: 'expert', source: 'military-expertise' },
    { level: 7, track: 'classDc', rank: 'expert', source: 'expert-tactician' },
    { level: 9, track: 'fortitude', rank: 'expert', source: 'fortitude-expertise' },
    { level: 11, track: 'will', rank: 'master', source: 'commanding-will' },
    { level: 11, track: 'unarmored', rank: 'expert', source: 'armor-expertise' },
    { level: 11, track: 'light', rank: 'expert', source: 'armor-expertise' },
    { level: 11, track: 'medium', rank: 'expert', source: 'armor-expertise' },
    { level: 11, track: 'heavy', rank: 'expert', source: 'armor-expertise' },
    { level: 13, track: 'perception', rank: 'master', source: 'perception-mastery' },
    { level: 13, track: 'unarmed', rank: 'master', source: 'weapon-mastery' },
    { level: 13, track: 'simple', rank: 'master', source: 'weapon-mastery' },
    { level: 13, track: 'martial', rank: 'master', source: 'weapon-mastery' },
    { level: 15, track: 'reflex', rank: 'master', source: 'battlefield-intuition' },
    { level: 15, track: 'classDc', rank: 'master', source: 'master-tactician' },
    { level: 17, track: 'unarmored', rank: 'master', source: 'armor-mastery' },
    { level: 17, track: 'light', rank: 'master', source: 'armor-mastery' },
    { level: 17, track: 'medium', rank: 'master', source: 'armor-mastery' },
    { level: 17, track: 'heavy', rank: 'master', source: 'armor-mastery' },
    { level: 19, track: 'classDc', rank: 'legendary', source: 'legendary-tactician' },
  ],
  exemplar: [
    { level: 5, track: 'unarmed', rank: 'expert', source: 'weapon-expertise' },
    { level: 5, track: 'simple', rank: 'expert', source: 'weapon-expertise' },
    { level: 5, track: 'martial', rank: 'expert', source: 'weapon-expertise' },
    { level: 7, track: 'will', rank: 'master', source: 'unassailable-soul' },
    { level: 9, track: 'perception', rank: 'expert', source: 'perception-expertise' },
    { level: 9, track: 'reflex', rank: 'expert', source: 'divine-premonition' },
    { level: 9, track: 'classDc', rank: 'expert', source: 'godly-expertise' },
    { level: 13, track: 'will', rank: 'legendary', source: 'greater-unassailable-soul' },
    { level: 13, track: 'unarmed', rank: 'master', source: 'divine-weapon-mastery' },
    { level: 13, track: 'simple', rank: 'master', source: 'divine-weapon-mastery' },
    { level: 13, track: 'martial', rank: 'master', source: 'divine-weapon-mastery' },
    { level: 13, track: 'unarmored', rank: 'expert', source: 'burnished-armor-expertise' },
    { level: 13, track: 'light', rank: 'expert', source: 'burnished-armor-expertise' },
    { level: 13, track: 'medium', rank: 'expert', source: 'burnished-armor-expertise' },
    { level: 15, track: 'fortitude', rank: 'master', source: 'mortality-reforged' },
    { level: 17, track: 'perception', rank: 'master', source: 'perception-mastery' },
    { level: 17, track: 'classDc', rank: 'master', source: 'deific-mastery' },
    { level: 19, track: 'unarmored', rank: 'master', source: 'burnished-armor-mastery' },
    { level: 19, track: 'light', rank: 'master', source: 'burnished-armor-mastery' },
    { level: 19, track: 'medium', rank: 'master', source: 'burnished-armor-mastery' },
  ],
  guardian: [
    { level: 5, track: 'unarmed', rank: 'expert', source: 'weapon-expertise' },
    { level: 5, track: 'simple', rank: 'expert', source: 'weapon-expertise' },
    { level: 5, track: 'martial', rank: 'expert', source: 'weapon-expertise' },
    { level: 5, track: 'medium', rank: 'expert', source: 'unbreakable-expertise' },
    { level: 5, track: 'heavy', rank: 'expert', source: 'unbreakable-expertise' },
    { level: 7, track: 'perception', rank: 'expert', source: 'reaction-time' },
    { level: 7, track: 'reflex', rank: 'expert', source: 'reflex-expertise' },
    { level: 9, track: 'fortitude', rank: 'master', source: 'battle-hardened' },
    { level: 9, track: 'classDc', rank: 'expert', source: 'guardian-expertise' },
    { level: 11, track: 'unarmored', rank: 'expert', source: 'unbreakable-mastery' },
    { level: 11, track: 'light', rank: 'expert', source: 'unbreakable-mastery' },
    { level: 11, track: 'medium', rank: 'master', source: 'unbreakable-mastery' },
    { level: 11, track: 'heavy', rank: 'master', source: 'unbreakable-mastery' },
    { level: 13, track: 'unarmed', rank: 'master', source: 'weapon-mastery' },
    { level: 13, track: 'simple', rank: 'master', source: 'weapon-mastery' },
    { level: 13, track: 'martial', rank: 'master', source: 'weapon-mastery' },
    { level: 15, track: 'unarmored', rank: 'master', source: 'unbreakable-legend' },
    { level: 15, track: 'light', rank: 'master', source: 'unbreakable-legend' },
    { level: 15, track: 'medium', rank: 'legendary', source: 'unbreakable-legend' },
    { level: 15, track: 'heavy', rank: 'legendary', source: 'unbreakable-legend' },
    { level: 17, track: 'will', rank: 'master', source: 'unyielding-resolve' },
    { level: 19, track: 'classDc', rank: 'master', source: 'guardian-mastery' },
  ],
  gunslinger: [
    { level: 3, track: 'will', rank: 'expert', source: 'stubborn' },
    { level: 5, track: 'unarmed', rank: 'expert', source: 'gunslinger-weapon-mastery' },
    { level: 5, track: 'simple', rank: 'master', source: 'gunslinger-weapon-mastery' },
    { level: 5, track: 'martial', rank: 'master', source: 'gunslinger-weapon-mastery' },
    { level: 5, track: 'advanced', rank: 'expert', source: 'gunslinger-weapon-mastery' },
    { level: 7, track: 'perception', rank: 'master', source: 'perception-mastery' },
    { level: 9, track: 'classDc', rank: 'expert', source: 'gunslinger-expertise' },
    { level: 11, track: 'reflex', rank: 'master', source: 'blast-dodger' },
    { level: 13, track: 'unarmed', rank: 'master', source: 'gunslinging-legend' },
    { level: 13, track: 'simple', rank: 'legendary', source: 'gunslinging-legend' },
    { level: 13, track: 'martial', rank: 'legendary', source: 'gunslinging-legend' },
    { level: 13, track: 'advanced', rank: 'master', source: 'gunslinging-legend' },
    { level: 13, track: 'unarmored', rank: 'expert', source: 'medium-armor-expertise' },
    { level: 13, track: 'light', rank: 'expert', source: 'medium-armor-expertise' },
    { level: 13, track: 'medium', rank: 'expert', source: 'medium-armor-expertise' },
    { level: 17, track: 'fortitude', rank: 'master', source: 'lead-constitution' },
    { level: 17, track: 'classDc', rank: 'master', source: 'shootists-edge' },
    { level: 19, track: 'perception', rank: 'legendary', source: 'perception-legend' },
    { level: 19, track: 'unarmored', rank: 'master', source: 'medium-armor-mastery' },
    { level: 19, track: 'light', rank: 'master', source: 'medium-armor-mastery' },
    { level: 19, track: 'medium', rank: 'master', source: 'medium-armor-mastery' },
  ],
  inventor: [
    { level: 5, track: 'unarmed', rank: 'expert', source: 'inventor-weapon-expertise' },
    { level: 5, track: 'simple', rank: 'expert', source: 'inventor-weapon-expertise' },
    { level: 5, track: 'martial', rank: 'expert', source: 'inventor-weapon-expertise' },
    { level: 7, track: 'reflex', rank: 'expert', source: 'reflex-expertise' },
    { level: 9, track: 'classDc', rank: 'expert', source: 'inventive-expertise' },
    { level: 11, track: 'will', rank: 'master', source: 'churning-mind' },
    { level: 11, track: 'unarmored', rank: 'expert', source: 'medium-armor-expertise-inventor' },
    { level: 11, track: 'light', rank: 'expert', source: 'medium-armor-expertise-inventor' },
    { level: 11, track: 'medium', rank: 'expert', source: 'medium-armor-expertise-inventor' },
    { level: 13, track: 'perception', rank: 'expert', source: 'perception-expertise' },
    { level: 13, track: 'unarmed', rank: 'master', source: 'inventor-weapon-mastery' },
    { level: 13, track: 'simple', rank: 'master', source: 'inventor-weapon-mastery' },
    { level: 13, track: 'martial', rank: 'master', source: 'inventor-weapon-mastery' },
    { level: 17, track: 'fortitude', rank: 'master', source: 'anvils-hardness' },
    { level: 17, track: 'classDc', rank: 'master', source: 'inventive-mastery' },
    { level: 19, track: 'unarmored', rank: 'master', source: 'medium-armor-mastery' },
    { level: 19, track: 'light', rank: 'master', source: 'medium-armor-mastery' },
    { level: 19, track: 'medium', rank: 'master', source: 'medium-armor-mastery' },
  ],
  investigator: [
    { level: 5, track: 'unarmed', rank: 'expert', source: 'weapon-expertise' },
    { level: 5, track: 'simple', rank: 'expert', source: 'weapon-expertise' },
    { level: 5, track: 'martial', rank: 'expert', source: 'weapon-expertise' },
    { level: 7, track: 'perception', rank: 'master', source: 'perception-mastery' },
    { level: 9, track: 'fortitude', rank: 'expert', source: 'fortitude-expertise' },
    { level: 9, track: 'classDc', rank: 'expert', source: 'investigator-expertise' },
    { level: 11, track: 'will', rank: 'master', source: 'dogged-will' },
    { level: 13, track: 'perception', rank: 'legendary', source: 'perception-legend' },
    { level: 13, track: 'unarmed', rank: 'master', source: 'martial-weapon-mastery' },
    { level: 13, track: 'simple', rank: 'master', source: 'martial-weapon-mastery' },
    { level: 13, track: 'martial', rank: 'master', source: 'martial-weapon-mastery' },
    { level: 13, track: 'unarmored', rank: 'expert', source: 'light-armor-expertise' },
    { level: 13, track: 'light', rank: 'expert', source: 'light-armor-expertise' },
    { level: 15, track: 'reflex', rank: 'master', source: 'savvy-reflexes' },
    { level: 17, track: 'will', rank: 'legendary', source: 'greater-dogged-will' },
    { level: 19, track: 'classDc', rank: 'master', source: 'master-detective' },
    { level: 19, track: 'unarmored', rank: 'master', source: 'light-armor-mastery' },
    { level: 19, track: 'light', rank: 'master', source: 'light-armor-mastery' },
  ],
  kineticist: [
    { level: 3, track: 'will', rank: 'expert', source: 'will-expertise' },
    { level: 7, track: 'fortitude', rank: 'master', source: 'kinetic-durability' },
    { level: 7, track: 'classDc', rank: 'expert', source: 'kinetic-expertise' },
    { level: 9, track: 'perception', rank: 'expert', source: 'perception-expertise' },
    { level: 11, track: 'reflex', rank: 'master', source: 'kinetic-quickness' },
    { level: 11, track: 'unarmed', rank: 'expert', source: 'weapon-expertise' },
    { level: 11, track: 'simple', rank: 'expert', source: 'weapon-expertise' },
    { level: 13, track: 'unarmored', rank: 'expert', source: 'light-armor-expertise' },
    { level: 13, track: 'light', rank: 'expert', source: 'light-armor-expertise' },
    { level: 15, track: 'fortitude', rank: 'legendary', source: 'greater-kinetic-durability' },
    { level: 15, track: 'classDc', rank: 'master', source: 'kinetic-mastery' },
    { level: 19, track: 'classDc', rank: 'legendary', source: 'kinetic-legend' },
    { level: 19, track: 'unarmored', rank: 'master', source: 'light-armor-mastery' },
    { level: 19, track: 'light', rank: 'master', source: 'light-armor-mastery' },
  ],
  magus: [
    { level: 5, track: 'reflex', rank: 'expert', source: 'lightning-reflexes' },
    { level: 5, track: 'unarmed', rank: 'expert', source: 'weapon-expertise' },
    { level: 5, track: 'simple', rank: 'expert', source: 'weapon-expertise' },
    { level: 5, track: 'martial', rank: 'expert', source: 'weapon-expertise' },
    { level: 9, track: 'perception', rank: 'expert', source: 'alertness' },
    { level: 9, track: 'will', rank: 'master', source: 'resolve' },
    { level: 9, track: 'spellcasting', rank: 'expert', source: 'expert-spellcaster' },
    { level: 11, track: 'unarmored', rank: 'expert', source: 'medium-armor-expertise' },
    { level: 11, track: 'light', rank: 'expert', source: 'medium-armor-expertise' },
    { level: 11, track: 'medium', rank: 'expert', source: 'medium-armor-expertise' },
    { level: 13, track: 'unarmed', rank: 'master', source: 'weapon-mastery' },
    { level: 13, track: 'simple', rank: 'master', source: 'weapon-mastery' },
    { level: 13, track: 'martial', rank: 'master', source: 'weapon-mastery' },
    { level: 15, track: 'fortitude', rank: 'master', source: 'juggernaut' },
    { level: 17, track: 'spellcasting', rank: 'master', source: 'master-spellcaster' },
    { level: 17, track: 'unarmored', rank: 'master', source: 'medium-armor-mastery' },
    { level: 17, track: 'light', rank: 'master', source: 'medium-armor-mastery' },
    { level: 17, track: 'medium', rank: 'master', source: 'medium-armor-mastery' },
  ],
  monk: [
    { level: 5, track: 'perception', rank: 'expert', source: 'perception-expertise' },
    { level: 5, track: 'unarmed', rank: 'expert', source: 'expert-strikes' },
    { level: 5, track: 'simple', rank: 'expert', source: 'expert-strikes' },
    { level: 9, track: 'classDc', rank: 'expert', source: 'monk-expertise' },
    { level: 13, track: 'unarmed', rank: 'master', source: 'master-strikes' },
    { level: 13, track: 'simple', rank: 'master', source: 'master-strikes' },
    { level: 13, track: 'unarmored', rank: 'master', source: 'graceful-mastery' },
    { level: 17, track: 'classDc', rank: 'master', source: 'graceful-legend' },
    { level: 17, track: 'unarmored', rank: 'legendary', source: 'graceful-legend' },
  ],
  oracle: [
    { level: 7, track: 'will', rank: 'master', source: 'mysterious-resolve' },
    { level: 7, track: 'spellcasting', rank: 'expert', source: 'expert-spellcaster' },
    { level: 9, track: 'fortitude', rank: 'expert', source: 'magical-fortitude' },
    { level: 11, track: 'perception', rank: 'expert', source: 'oracular-senses' },
    { level: 11, track: 'unarmed', rank: 'expert', source: 'weapon-expertise' },
    { level: 11, track: 'simple', rank: 'expert', source: 'weapon-expertise' },
    { level: 13, track: 'reflex', rank: 'expert', source: 'premonition-reflexes' },
    { level: 13, track: 'unarmored', rank: 'expert', source: 'light-armor-expertise' },
    { level: 13, track: 'light', rank: 'expert', source: 'light-armor-expertise' },
    { level: 15, track: 'spellcasting', rank: 'master', source: 'master-spellcaster' },
    { level: 17, track: 'will', rank: 'legendary', source: 'greater-mysterious-resolve' },
    { level: 19, track: 'spellcasting', rank: 'legendary', source: 'legendary-spellcaster' },
  ],
  psychic: [
    { level: 5, track: 'reflex', rank: 'expert', source: 'precognitive-reflexes' },
    { level: 7, track: 'spellcasting', rank: 'expert', source: 'expert-spellcaster' },
    { level: 9, track: 'fortitude', rank: 'expert', source: 'fortitude-expertise' },
    { level: 11, track: 'perception', rank: 'expert', source: 'extrasensory-perception' },
    { level: 11, track: 'will', rank: 'master', source: 'walls-of-will' },
    { level: 11, track: 'unarmed', rank: 'expert', source: 'weapon-expertise' },
    { level: 11, track: 'simple', rank: 'expert', source: 'weapon-expertise' },
    { level: 13, track: 'unarmored', rank: 'expert', source: 'personal-barrier' },
    { level: 15, track: 'spellcasting', rank: 'master', source: 'master-spellcaster' },
    { level: 17, track: 'will', rank: 'legendary', source: 'fortress-of-will' },
    { level: 19, track: 'spellcasting', rank: 'legendary', source: 'legendary-spellcaster' },
  ],
  sorcerer: [
    { level: 5, track: 'fortitude', rank: 'expert', source: 'magical-fortitude' },
    { level: 7, track: 'spellcasting', rank: 'expert', source: 'expert-spellcaster' },
    { level: 9, track: 'reflex', rank: 'expert', source: 'reflex-expertise' },
    { level: 11, track: 'perception', rank: 'expert', source: 'perception-expertise' },
    { level: 11, track: 'unarmed', rank: 'expert', source: 'weapon-expertise' },
    { level: 11, track: 'simple', rank: 'expert', source: 'weapon-expertise' },
    { level: 13, track: 'unarmored', rank: 'expert', source: 'defensive-robes' },
    { level: 15, track: 'spellcasting', rank: 'master', source: 'master-spellcaster' },
    { level: 17, track: 'will', rank: 'master', source: 'majestic-will' },
    { level: 19, track: 'spellcasting', rank: 'legendary', source: 'legendary-spellcaster' },
  ],
  summoner: [
    { level: 3, track: 'perception', rank: 'expert', source: 'shared-vigilance' },
    { level: 9, track: 'reflex', rank: 'expert', source: 'shared-reflexes' },
    { level: 9, track: 'spellcasting', rank: 'expert', source: 'expert-spellcaster' },
    { level: 11, track: 'fortitude', rank: 'master', source: 'twin-juggernauts' },
    { level: 11, track: 'unarmed', rank: 'expert', source: 'simple-weapon-expertise' },
    { level: 11, track: 'simple', rank: 'expert', source: 'simple-weapon-expertise' },
    { level: 13, track: 'unarmored', rank: 'expert', source: 'defensive-robes' },
    { level: 15, track: 'will', rank: 'master', source: 'shared-resolve' },
    { level: 17, track: 'spellcasting', rank: 'master', source: 'master-spellcaster' },
  ],
  swashbuckler: [
    { level: 3, track: 'fortitude', rank: 'expert', source: 'fortitude-expertise' },
    { level: 5, track: 'unarmed', rank: 'expert', source: 'weapon-expertise' },
    { level: 5, track: 'simple', rank: 'expert', source: 'weapon-expertise' },
    { level: 5, track: 'martial', rank: 'expert', source: 'weapon-expertise' },
    { level: 7, track: 'reflex', rank: 'master', source: 'confident-evasion' },
    { level: 9, track: 'classDc', rank: 'expert', source: 'swashbuckler-expertise' },
    { level: 11, track: 'perception', rank: 'master', source: 'vigilant-senses' },
    { level: 13, track: 'reflex', rank: 'legendary', source: 'assured-evasion' },
    { level: 13, track: 'unarmed', rank: 'master', source: 'weapon-mastery' },
    { level: 13, track: 'simple', rank: 'master', source: 'weapon-mastery' },
    { level: 13, track: 'martial', rank: 'master', source: 'weapon-mastery' },
    { level: 13, track: 'unarmored', rank: 'expert', source: 'light-armor-expertise' },
    { level: 13, track: 'light', rank: 'expert', source: 'light-armor-expertise' },
    { level: 17, track: 'will', rank: 'master', source: 'reinforced-ego' },
    { level: 19, track: 'classDc', rank: 'master', source: 'eternal-confidence' },
    { level: 19, track: 'unarmored', rank: 'master', source: 'light-armor-mastery' },
    { level: 19, track: 'light', rank: 'master', source: 'light-armor-mastery' },
  ],
  thaumaturge: [
    { level: 3, track: 'reflex', rank: 'expert', source: 'reflex-expertise' },
    { level: 5, track: 'unarmed', rank: 'expert', source: 'weapon-expertise' },
    { level: 5, track: 'simple', rank: 'expert', source: 'weapon-expertise' },
    { level: 5, track: 'martial', rank: 'expert', source: 'weapon-expertise' },
    { level: 7, track: 'will', rank: 'master', source: 'disciplined-mind' },
    { level: 9, track: 'perception', rank: 'master', source: 'perception-mastery' },
    { level: 9, track: 'classDc', rank: 'expert', source: 'thaumaturgic-expertise' },
    { level: 11, track: 'unarmored', rank: 'expert', source: 'medium-armor-expertise' },
    { level: 11, track: 'light', rank: 'expert', source: 'medium-armor-expertise' },
    { level: 11, track: 'medium', rank: 'expert', source: 'medium-armor-expertise' },
    { level: 13, track: 'will', rank: 'legendary', source: 'perfected-mind' },
    { level: 13, track: 'unarmed', rank: 'master', source: 'weapon-mastery' },
    { level: 13, track: 'simple', rank: 'master', source: 'weapon-mastery' },
    { level: 13, track: 'martial', rank: 'master', source: 'weapon-mastery' },
    { level: 15, track: 'fortitude', rank: 'master', source: 'earned-resilience' },
    { level: 17, track: 'classDc', rank: 'master', source: 'thaumaturgic-mastery' },
    { level: 19, track: 'unarmored', rank: 'master', source: 'medium-armor-mastery' },
    { level: 19, track: 'light', rank: 'master', source: 'medium-armor-mastery' },
    { level: 19, track: 'medium', rank: 'master', source: 'medium-armor-mastery' },
  ],
};
