/*
 * Feat-granted SKILL proficiencies — auto-generated from Foundry rule elements (Remaster pf2e packs).
 *
 * Extends FEAT_GRANTS beyond the 7 hand-authored cases. Each entry is a feat that unconditionally
 * trains (or raises) a specific skill, derived from the feat's ActiveEffectLike rule elements on
 * `system.skills.<skill>.rank` (value 1=trained, 2=expert, 3=master, 4=legendary), or a skill-training
 * CHOICE (a ChoiceSet feeding `system.skills.{item|…}.rank`) surfaced as a picker in the builder.
 *
 * Scope: ONLY unconditional skill grants. Predicated (situational) rules are excluded; weapon grants
 * (MartialProficiency — a bespoke proficiency that doesn't map cleanly to HH weapon categories) and
 * formula-valued armor cascades (Sentinel-style) are NOT auto-mapped and stay hand-authored in
 * FEAT_GRANTS. Grants RAISE only (like all FEAT_GRANTS), so a redundant train is a no-op. Restricted
 * skill choices are surfaced as `options: 'any'` (the player picks; the exact list restriction is not modeled).
 *
 * Regenerate: scripts/scratch prof-extract.mjs. To override a specific feat, add it to FEAT_GRANTS —
 * hand-authored entries win the merge.
 */
import type { FeatGrant } from './featGrants';

export const FEAT_SKILL_GRANTS: Record<string, FeatGrant> = {
  'acrobat-dedication': { skills: { acrobatics: 'expert' }, rankUpgrade: { level: 15, rank: 'legendary' } },
  // "Choose a Lore skill subcategory. You become trained in it. At 3rd, 7th, and 15th levels, you
  // gain an additional skill increase you can apply ONLY to the chosen Lore subcategory."
  // (AoN feat-5114.) The increase is spendable nowhere else, so the ladder IS the rank — and 3/7/15
  // are exactly the levels at which a skill increase may reach expert/master/legendary. Read
  // through `at()` in build.ts's Lore loop and announced on the builder's level card by
  // featUpgradesAtLevel. Measured before: a level-20 holder read "Warfare Lore, trained".
  'additional-lore': { loreChoices: 1, rankUpgrade: [{ level: 3, rank: 'expert' }, { level: 7, rank: 'master' }, { level: 15, rank: 'legendary' }] },
  'adroit-manipulation': { skills: { thievery: 'trained' }, redundantFallback: true },
  'alchemist-dedication': { skills: { crafting: 'trained' }, redundantFallback: true },
  'aldori-duelist-dedication': { skills: { 'lore:dueling': 'trained' }, skillChoices: [{ options: ['acrobatics', 'athletics'], rank: 'trained' }], redundantFallback: true },
  'alkenstar-agent-dedication': { skills: { deception: 'expert', 'lore:underworld': 'trained' }, redundantFallback: true },
  'alter-ego-dedication': { skills: { deception: 'expert' } },
  'anadi-lore': { skills: { crafting: 'trained', survival: 'trained', 'lore:anadi': 'trained' }, redundantFallback: true },
  'android-lore': { skills: { crafting: 'trained', thievery: 'trained', 'lore:android': 'trained' }, redundantFallback: true },
  'angelkin': { skills: { society: 'trained' }, redundantFallback: true },
  'animal-actor': { conditionalSkills: { nature: { base: 'trained', upgraded: 'expert' } }, loreChoices: 1 },
  'aon-grippli-lore': { skills: { nature: 'trained', stealth: 'trained', 'lore:grippli': 'trained' }, redundantFallback: true },
  /* ---- ancestry weapon EXPERTISE ------------------------------------------------------------
   * "Whenever you gain a class feature that grants you expert or greater proficiency in a given
   * weapon or weapons, you also gain that proficiency in <list>."
   *
   * These MIRROR the character's own best weapon-category rank rather than granting a fixed one, so
   * a 1st-level holder gains nothing extra and a fighter's weapon mastery carries through by itself.
   * A flat `rank: 'expert'` would hand expert proficiency to a character who has not earned it, so
   * `mirrorBestCategory` is the only correct shape here. Every weapon id checked against core.json.
   */
  'gnoll-weapon-expertise': { weaponFamiliarity: { weapons: ['flail', 'khopesh', 'mambele', 'spear', 'war-flail'], mirrorBestCategory: true } },
  'gnome-weapon-expertise': { weaponFamiliarity: { weapons: ['glaive', 'kukri'], mirrorBestCategory: true } },
  'goblin-weapon-expertise': { weaponFamiliarity: { weapons: ['dogslicer', 'horsechopper'], mirrorBestCategory: true } },
  'halfling-weapon-expertise': { weaponFamiliarity: { weapons: ['sling', 'halfling-sling-staff', 'shortsword'], mirrorBestCategory: true } },
  'orc-weapon-expertise': { weaponFamiliarity: { weapons: ['falchion', 'greataxe'], mirrorBestCategory: true } },
  'vanths-weapon-expertise': { weaponFamiliarity: { weapons: ['bo-staff', 'longbow', 'composite-longbow', 'scythe', 'staff'], mirrorBestCategory: true } },
  'lions-might': { weaponFamiliarity: { weapons: ['lion-scythe', 'sun-sling'], mirrorBestCategory: true } },
  'azarketi-weapon-expertise': { weaponFamiliarity: { weapons: ['crossbow', 'hand-crossbow', 'longspear', 'spear', 'trident', 'boarding-axe', 'gill-hook'], mirrorBestCategory: true } },
  'dwarven-weapon-expertise': { weaponFamiliarity: { weapons: ['battle-axe', 'pick', 'warhammer', 'clan-dagger', 'clan-pistol', 'dwarven-scattergun', 'dwarven-dorn-dergar', 'dwarven-war-axe', 'dwarven-waraxe', 'long-hammer', 'wrecker', 'wrecker-melee', 'wrecker-ranged'], mirrorBestCategory: true } },
  'elven-weapon-expertise': { weaponFamiliarity: { weapons: ['longbow', 'composite-longbow', 'longsword', 'rapier', 'shortbow', 'composite-shortbow', 'elven-curve-blade', 'elven-branched-spear', 'dawnsilver-tree', 'three-peaked-tree', 'three-peaked-tree-melee', 'three-peaked-tree-ranged'], mirrorBestCategory: true } },
  'arcana-of-iron': { weapon: { advanced: 'trained' } },
  'arcane-dragonblood': { skills: { arcana: 'trained' }, redundantFallback: true },
  'arcane-evolution': { skillChoices: [{ options: 'any', rank: 'trained' }] },
  'archaeologist-dedication': { skills: { society: 'expert', thievery: 'expert' } },
  'armigers-protection': { armor: { light: 'trained', medium: 'trained' } },
  'artisanal-crafter': { skills: { crafting: 'trained' }, redundantFallback: true },
  'athamaru-lore': { skills: { athletics: 'trained', nature: 'trained' }, redundantFallback: true },
  'automaton-lore': { skills: { arcana: 'trained', crafting: 'trained' }, redundantFallback: true },
  'avowed-insight': { loreChoices: 1 },
  'awakened-animal-lore': { skills: { arcana: 'trained', nature: 'trained' }, redundantFallback: true },
  'axiomatic-lore': { skills: { diplomacy: 'trained', society: 'trained', 'lore:axis': 'trained' }, redundantFallback: true },
  'azarketi-lore': { skills: { athletics: 'trained', nature: 'trained', 'lore:azarketi': 'trained' }, redundantFallback: true },
  'azarketi-weapon-familiarity': { weaponFamiliarity: {'weapons':['crossbow','hand-crossbow','longspear','spear','trident','boarding-axe','gill-hook'],'rank':'trained'} },
  'barbarian-dedication': { skills: { athletics: 'trained' }, redundantFallback: true },
  'bard-dedication': { skills: { occultism: 'trained', performance: 'trained' }, redundantFallback: true },
  // "You are trained in Bardic Lore, a special Lore skill… If you have legendary proficiency in
  // OCCULTISM, you gain expert proficiency in Bardic Lore, but you can't increase your proficiency
  // rank in Bardic Lore by any other means." Two clauses, neither of which a flat `skills` grant
  // could say: the expert step is gated on a DIFFERENT skill (crossConditionalSkills, read in
  // build.ts's grant loop), and the lock lives in LOCKED_SKILL_KEYS (featGrants.ts) because it
  // has to reach the skill-increase loop and the builder, not this table.
  'bardic-lore': { skills: { 'lore:bardic': 'trained' }, crossConditionalSkills: { 'lore:bardic': { whenSkill: 'occultism', whenRank: 'legendary', rank: 'expert' } } },
  'battle-harbinger-dedication': { skillChoices: [{ options: 'any', rank: 'trained' }], redundantFallback: true },
  'battleblooded': { skills: { intimidation: 'trained' }, redundantFallback: true },
  'beast-trainer': { skills: { nature: 'trained' } },
  'beastbrood': { skills: { society: 'trained' }, redundantFallback: true },
  'blackjacket-dedication': { skills: { 'lore:warfare': 'trained' }, conditionalSkills: { intimidation: { base: 'trained', upgraded: 'expert' } }, redundantFallback: true },
  'bloodrager': { skills: { athletics: 'trained', medicine: 'trained' } },
  'bloodrager-dedication': { skillChoices: [{ options: 'any', rank: 'trained' }], redundantFallback: true },
  'bouncy-goblin': { skills: { acrobatics: 'trained' }, redundantFallback: true },
  'bright-lion-dedication': { conditionalSkills: { 'lore:mzali': { base: 'trained', upgraded: 'expert' } }, skillChoices: [{ options: ['deception', 'diplomacy'], rank: 'trained' }] },
  'brilliant-crafter': { skills: { crafting: 'expert' } },
  'butterfly-blade-dedication': { conditionalSkills: { deception: { base: 'trained', upgraded: 'expert' }, stealth: { base: 'trained', upgraded: 'expert' } } },
  'campfire-chronicler-dedication': { skills: { religion: 'trained', survival: 'trained' }, redundantFallback: true },
  'captain-dedication': { skillChoices: [{ options: ['diplomacy', 'intimidation'], rank: 'trained' }], redundantFallback: true },
  'captivator-dedication': { skillChoices: [{ options: ['deception', 'diplomacy'], rank: 'trained' }] },
  'caretakers-intuition': { skills: { nature: 'trained' }, redundantFallback: true },
  'catch-the-details': { skills: { society: 'trained' }, redundantFallback: true },
  'catfolk-lore': { skills: { acrobatics: 'trained', survival: 'trained', 'lore:catfolk': 'trained' }, redundantFallback: true },
  'catfolk-weapon-expertise': { weaponFamiliarity: {'weapons':['kama','kukri','scimitar','sickle','claw-blade','whip-claw'],'mirrorBestCategory':true} },
  'centaur-lore': { skills: { medicine: 'trained', nature: 'trained', 'lore:centaur': 'trained' }, redundantFallback: true },
  'champion-dedication': { skills: { religion: 'trained' }, armor: { light: 'trained', medium: 'trained' }, redundantFallback: true },
  'changeling-lore': { skills: { deception: 'trained', occultism: 'trained', 'lore:hag': 'trained' }, redundantFallback: true },
  'childlike-plant': { skills: { deception: 'trained' }, redundantFallback: true },
  'clan-lore': { skillChoices: [{ options: ['arcana', 'athletics', 'crafting', 'diplomacy', 'intimidation', 'medicine', 'nature', 'occultism', 'religion', 'society', 'survival', 'thievery'], rank: 'trained' }, { options: ['arcana', 'athletics', 'crafting', 'diplomacy', 'intimidation', 'medicine', 'nature', 'occultism', 'religion', 'society', 'survival', 'thievery'], rank: 'trained' }], loreChoices: 1, redundantFallback: true },
  'clan-pistol': { weaponFamiliarity: {'weapons':['clan-pistol'],'rank':'trained'} },
  'cleric-dedication': { skills: { religion: 'trained' }, skillChoices: [{ options: 'any', rank: 'trained' }], redundantFallback: true },
  'commander-dedication': { skills: { 'lore:warfare': 'trained' } },
  'conrasu-lore': { skills: { crafting: 'trained', occultism: 'trained', 'lore:conrasu': 'trained' }, redundantFallback: true },
  'conrasu-weapon-expertise': { weaponFamiliarity: {'weapons':['composite-shortbow','glaive','longspear','longsword','shortbow','spear','buugeng','taw-launcher'],'mirrorBestCategory':true} },
  'conrasu-weapon-familiarity': { weaponFamiliarity: {'weapons':['composite-shortbow','glaive','longspear','longsword','shortbow','spear','buugeng','taw-launcher'],'rank':'trained'} },
  'corpse-tender-dedication': { skills: { diplomacy: 'trained' }, redundantFallback: true },
  'crafter-in-the-vault': { skills: { 'lore:architecture': 'trained', 'lore:engineering': 'trained' } },
  'creative-prodigy': { skills: { performance: 'trained', deception: 'trained', 'lore:art': 'trained' }, redundantFallback: true },
  'crossbow-infiltrator-dedication': { weaponFamiliarity: {'weapons':['gauntlet-bow','hand-crossbow','repeating-hand-crossbow'],'mirrorBestCategory':true} },
  'cultivator-dedication': { skills: { occultism: 'expert' } },
  'dandy-dedication': { conditionalSkills: { deception: { base: 'trained', upgraded: 'expert' }, society: { base: 'trained', upgraded: 'expert' } } },
  'demolitionist-dedication': { conditionalSkills: { 'lore:engineering': { base: 'trained', upgraded: 'expert' } } },
  'devils-eye': { skills: { 'lore:legal': 'expert' } },
  'diverse-armor-expert': { armor: { light: 'expert', medium: 'expert', heavy: 'expert', unarmored: 'expert' } },
  'divine-dragonblood': { skills: { religion: 'trained' }, redundantFallback: true },
  'draconic-acolyte-dedication': { skills: { 'lore:dragon': 'trained' } },
  'dragon-lore': { skills: { diplomacy: 'trained', intimidation: 'trained' }, redundantFallback: true },
  'dragonscaled-lore': { skills: { intimidation: 'trained', 'lore:dragon': 'trained' }, skillChoices: [{ options: ['arcana', 'nature', 'occultism', 'religion'], rank: 'trained' }], redundantFallback: true },
  'druid-dedication': { skills: { nature: 'trained' }, skillChoices: [{ options: 'any', rank: 'trained' }], redundantFallback: true },
  'dual-studies': { skillChoices: [{ options: 'any', rank: 'trained' }], rankUpgrade: { level: 7, rank: 'expert' } },
  'duskwalker-lore': { skills: { medicine: 'trained', religion: 'trained', 'lore:boneyard': 'trained' }, redundantFallback: true },
  'dustsoul': { skills: { survival: 'trained' }, redundantFallback: true },
  // The live record prints *"the Additional Lore general feat for DWARF Lore"* (Remaster renamed
  // Dwarven Lore → Dwarf Lore). The direct grant kept the legacy key, so binding the vehicle to the
  // printed subject would have put TWO Lore rows on the sheet. Renamed to agree with the sentence.
  'dwarven-lore': { skills: { crafting: 'trained', religion: 'trained', 'lore:dwarf': 'trained' }, redundantFallback: true },
  'eagle-knight-dedication': { skills: { 'lore:politics': 'trained' } },
  'earned-glory': { skills: { performance: 'trained' }, redundantFallback: true },
  'echo-of-lost-moments': { skills: { 'lore:fortune-telling': 'trained', 'lore:genealogy': 'trained' } },
  'edgewatch-detective-dedication': { skillChoices: [{ options: 'any', rank: 'trained' }, { options: 'any', rank: 'trained' }, { options: 'any', rank: 'trained' }], redundantFallback: true },
  'eldritch-researcher-dedication': { skillChoices: [{ options: ['arcana', 'occultism'], rank: 'expert' }] },
  'elemental-embellish': { skills: { intimidation: 'trained' }, redundantFallback: true },
  'elemental-lore': { skills: { survival: 'trained' }, skillChoices: [{ options: ['arcana', 'nature'], rank: 'trained' }], loreChoices: 1, redundantFallback: true },
  'elemental-trade': { skills: { crafting: 'trained' }, redundantFallback: true },
  // *"…for ELF Lore"* — same Remaster rename as dwarven-lore above.
  'elven-lore': { skills: { arcana: 'trained', nature: 'trained', 'lore:elf': 'trained' }, redundantFallback: true },
  'embodied-legionary-subjectivity': { skills: { arcana: 'trained', athletics: 'trained', 'lore:warfare': 'trained' } },
  'evasiveness-rogue': { save: { reflex: 'master' } },
  'executioner-weapon-training': { weaponFamiliarity: {'weapons':['battle-axe','falchion','greataxe','scimitar'],'mirrorBestCategory':true} },
  'exemplar-dedication': { weapon: { martial: 'trained' } },
  'expert-overdrive': { skills: { crafting: 'expert' } },
  'extra-squishy': { skills: { acrobatics: 'trained' }, redundantFallback: true },
  'eye-for-treasure': { skills: { crafting: 'trained' }, redundantFallback: true },
  'fan-dancer-dedication': { skills: { performance: 'expert' }, rankUpgrade: { level: 7, rank: 'master' } },
  'fascinated-by-society': { skills: { society: 'trained' }, redundantFallback: true },
  'fetchling-lore': { skills: { occultism: 'trained', stealth: 'trained', 'lore:shadow-plane': 'trained' }, redundantFallback: true },
  'field-propagandist-dedication': { conditionalSkills: { society: { base: 'trained', upgraded: 'expert' } } },
  'firework-technician-dedication': { conditionalSkills: { 'lore:fireworks': { base: 'trained', upgraded: 'expert' } } },
  'flexible-form': { skills: { acrobatics: 'trained' }, redundantFallback: true },
  'flexible-studies': { skillChoices: [{ options: 'any', rank: 'trained' }] },
  'folk-healer': { skills: { medicine: 'trained', occultism: 'trained' }, redundantFallback: true },
  'folktales-lore': { skills: { 'lore:folktales': 'trained' } },
  'gemsoul': { skills: { performance: 'trained' }, redundantFallback: true },
  'genie-weapon-expertise': { weaponFamiliarity: {'weapons':['falchion','ranseur','scimitar','trident','wish-blade','wish-knife'],'mirrorBestCategory':true} },
  'genie-weapon-familiarity': { weaponFamiliarity: {'weapons':['falchion','ranseur','scimitar','trident','wish-blade','wish-knife'],'rank':'trained'} },
  'ghoran-lore': { skills: { arcana: 'trained', nature: 'trained', 'lore:ghoran': 'trained' }, redundantFallback: true },
  'ghoran-weapon-expertise': { weaponFamiliarity: {'weapons':['glaive','greatclub','hatchet','scythe','sickle','thorn-whip'],'mirrorBestCategory':true} },
  'ghoran-weapon-familiarity': { weaponFamiliarity: {'weapons':['glaive','greatclub','hatchet','scythe','sickle','thorn-whip'],'rank':'trained'} },
  'gnome-obsession': { loreChoices: 1 },
  'goblin-lore': { skills: { nature: 'trained', stealth: 'trained', 'lore:goblin': 'trained' }, redundantFallback: true },
  'golden-league-xun-dedication': { skillChoices: [{ options: ['athletics', 'deception', 'intimidation', 'stealth'], rank: 'expert' }, { options: ['athletics', 'deception', 'intimidation', 'stealth'], rank: 'expert' }] },
  'golden-legionnaire-dedication': { skills: { 'lore:warfare': 'trained' } },
  'goloma-lore': { skills: { survival: 'trained', stealth: 'trained', 'lore:goloma': 'trained' }, redundantFallback: true },
  'gossip-lore': { skills: { 'lore:gossip': 'trained' } },
  'greenwatch-initiate': { skills: { survival: 'expert' } },
  'grippli-lore': { skills: { nature: 'trained', stealth: 'trained', 'lore:grippli': 'trained' }, redundantFallback: true },
  'grippli-weapon-expertise': { weaponFamiliarity: {'weapons':['blowgun','hatchet','scythe','shortbow','composite-shortbow'],'mirrorBestCategory':true} },
  'guardian-dedication': { skills: { athletics: 'trained' }, redundantFallback: true, armor: { light: 'trained', medium: 'trained' } },
  'guerrilla-dedication': { skillChoices: [{ options: ['deception', 'thievery'], rank: 'trained' }] },
  'gunslinger-dedication': { skillChoices: [{ options: ['acrobatics', 'deception', 'intimidation', 'stealth', 'athletics', 'thievery', 'arcana'], rank: 'trained' }], redundantFallback: true },
  'halfling-lore': { skills: { acrobatics: 'trained', stealth: 'trained', 'lore:halfling': 'trained' }, redundantFallback: true },
  'harbingers-protection': { armor: { heavy: 'trained' } },
  'harmless-doll': { skills: { deception: 'trained' }, redundantFallback: true },
  'harrower-dedication': { skills: { occultism: 'trained', 'lore:fortune-telling': 'trained' }, redundantFallback: true },
  'hellbreaker-dedication': { skills: { 'lore:devil': 'trained', 'lore:hellknight': 'trained' } },
  'hellknight-dedication': { conditionalSkills: { intimidation: { base: 'trained', upgraded: 'expert' } } },
  'hellknight-preferment': { skills: { intimidation: 'expert' } },
  'hellknight-signifer-preferment': { skills: { intimidation: 'expert' }, skillChoices: [{ options: ['arcana', 'nature', 'occultism', 'religion'], rank: 'expert' }] },
  'hellspawn': { skills: { deception: 'trained', 'lore:legal': 'trained' }, redundantFallback: true },
  'herbalist-dedication': { skills: { nature: 'expert' } },
  'hobgoblin-lore': { skills: { athletics: 'trained', crafting: 'trained', 'lore:hobgoblin': 'trained' }, redundantFallback: true },
  'hobgoblin-weapon-expertise': { weaponFamiliarity: {'weapons':['composite-longbow','composite-shortbow','glaive','longbow','longsword','shortbow','breaching-pike','phalanx-piercer','capturing-spetum'],'mirrorBestCategory':true} },
  'ice-crafter': { conditionalSkills: { crafting: { base: 'trained', upgraded: 'expert' } } },
  'idyllkin': { skills: { nature: 'trained' }, redundantFallback: true },
  'impostor-in-hidden-places': { skills: { 'lore:fortune-telling': 'trained', 'lore:underworld': 'trained' } },
  'initiate-benefit-tome': { skillChoices: [{ options: 'any', rank: 'trained' }, { options: 'any', rank: 'trained' }], rankUpgrade: { level: 5, rank: 'expert' } },
  'innocuous': { skills: { deception: 'trained' }, redundantFallback: true },
  'intuitive-crafting': { skills: { crafting: 'trained' }, redundantFallback: true },
  'inventor-dedication': { skills: { crafting: 'trained' } },
  'investigator-dedication': { skills: { society: 'trained' }, skillChoices: [{ options: 'any', rank: 'trained' }], redundantFallback: true },
  'invulnerable-rager': { armor: { heavy: 'trained' } },
  'jalmeri-heavenseeker-dedication': { skillChoices: [{ options: ['acrobatics', 'occultism'], rank: 'trained' }] },
  'jotunborn-grappler': { skills: { athletics: 'trained' }, redundantFallback: true },
  'jotunborn-lore': { skills: { occultism: 'trained', survival: 'trained', 'lore:jotunborn': 'trained' }, redundantFallback: true },
  'juggler-dedication': { skills: { performance: 'trained' }, redundantFallback: true },
  'kholo-lore': { skills: { stealth: 'trained', survival: 'trained' }, redundantFallback: true },
  'kineticist-dedication': { skills: { nature: 'trained' }, redundantFallback: true },
  'kitharodian-actor-dedication': { conditionalSkills: { society: { base: 'trained', upgraded: 'expert' }, 'lore:theater': { base: 'trained', upgraded: 'expert' } } },
  'kitsune-lore': { skills: { diplomacy: 'trained', deception: 'trained', 'lore:kitsune': 'trained' }, redundantFallback: true },
  'knight-reclaimant-dedication': { skills: { stealth: 'expert', survival: 'expert' } },
  'knight-vigilant-dedication': { skills: { religion: 'expert' } },
  'kobold-lore': { skills: { stealth: 'trained', thievery: 'trained', 'lore:kobold': 'trained' }, redundantFallback: true },
  'kobold-weapon-expertise': { weaponFamiliarity: {'weapons':['crossbow','greatpick','light-pick','pick','spear','fangwire','flying-talon','tricky-pick'],'mirrorBestCategory':true} },
  'lastwall-sentry-dedication': { conditionalSkills: { athletics: { base: 'trained', upgraded: 'expert' }, 'lore:undead': { base: 'trained', upgraded: 'expert' } } },
  'learn-by-watching': { skillChoices: [{ options: ['crafting', 'medicine', 'performance'], rank: 'trained' }] },
  'legendary-overdrive': { skills: { crafting: 'legendary' } },
  'legendary-tattoo-artist': { skills: { crafting: 'legendary' } },
  'lepidstadt-surgeon-dedication': { skills: { medicine: 'expert' } },
  'leshy-lore': { skills: { nature: 'trained', stealth: 'trained', 'lore:leshy': 'trained' }, redundantFallback: true },
  'linguist-dedication': { conditionalSkills: { society: { base: 'trained', upgraded: 'expert' } } },
  'lion-blade-dedication': { skills: { 'lore:espionage': 'trained' }, skillChoices: [{ options: ['deception', 'stealth'], rank: 'trained', conditionalRank: { base: 'trained', upgraded: 'expert' } }], redundantFallback: true },
  'living-monolith-dedication': { conditionalSkills: { 'lore:ancient-osirion': { base: 'trained', upgraded: 'expert' } } },
  'lizardfolk-lore': { skills: { nature: 'trained', survival: 'trained', 'lore:iruxi': 'trained' }, skillChoices: [{ options: ['nature', 'occultism'], rank: 'trained' }], redundantFallback: true },
  'loremaster-dedication': { skills: { 'lore:loremaster': 'trained' } },
  'lurker-in-devouring-dark': { skills: { 'lore:ocean': 'trained', 'lore:sailing': 'trained' } },
  'magaambyan-attendant-dedication': { skillChoices: [{ options: ['arcana', 'nature'], rank: 'trained' }] },
  'magic-warrior-dedication': { conditionalSkills: { 'lore:magic-warrior': { base: 'trained', upgraded: 'expert' } }, skillChoices: [{ options: ['arcana', 'nature'], rank: 'trained' }] },
  'magus-dedication': { skills: { arcana: 'trained' }, redundantFallback: true, weapon: { simple: 'trained' } },
  'marshal-dedication': { skillChoices: [{ options: ['diplomacy', 'intimidation'], rank: 'trained' }] },
  'martial-experience': { minLevel: 11, weapon: { unarmed: 'trained', simple: 'trained', martial: 'trained', advanced: 'trained' } },
  'mastermind': { skillChoices: [{ options: ['arcana', 'nature', 'occultism', 'religion'], rank: 'trained' }] },
  'merfolk-lore': { skills: { arcana: 'trained', society: 'trained', 'lore:merfolk': 'trained' }, redundantFallback: true },
  'minotaur-lore': { skills: { society: 'trained', stealth: 'trained', 'lore:minotaur': 'trained' }, redundantFallback: true },
  'miresoul': { skills: { acrobatics: 'trained' }, redundantFallback: true },
  'monarch-of-the-fey-courts': { skills: { 'lore:art': 'trained', 'lore:fey': 'trained' } },
  'monastic-archer-stance': { weaponFamiliarity: {'weapons':['longbow','shortbow','gakgung','bow-staff','bow-staff-ranged','mikazuki','mikazuki-ranged'],'mirrorBestCategory':true} },
  'monastic-weaponry': { weaponFamiliarity: {'weapons':['acrobats-staff','anchor-spear','ankhrav-duster','black-powder-knuckle-dusters','black-powder-knuckle-dusters-melee','black-powder-knuckle-dusters-ranged','bo-staff','boreal-staff','boreal-staff-greater','boreal-staff-major','bow-staff','bow-staff-melee','bow-staff-ranged','deepdread-claw','dragonscale-bo-staff','dragonscale-staff','fiendbreaker','fiendbreaker-heroic','fighting-fan','fulminating-spear','gakgung','gluttonous-spear','golden-blade-of-mzali','kama','katar','knuckle-duster','kusarigama','mikazuki','mikazuki-melee','mikazuki-ranged','monkeys-fist','nunchaku','nyctessas-staff','pantograph-gauntlet','phoenix-fighting-fan','piston-gauntlets','preordained-spear','purgatory-emissarys-staff','sai','sansetsukon','senseis-parasol','shadowpiercer','shuln-fang-katar','shuriken','skeletal-claw','snowcasters-staff','spear','spirit-fan','splintering-spear','splintering-spear-greater','splintering-spear-major','staff','staff-of-power','staff-of-sun-wukong','staff-of-the-dreamlands','staff-of-the-dreamlands-greater','staff-of-the-dreamlands-major','staff-of-the-magi','staff-of-the-ruling-beast','storm-herald','tekko-kagi','temple-sword','tonfa','tri-bladed-katar','twining-staff','twisting-gale','whipstaff'],'mirrorBestCategory':true} },
  'monk-dedication': { skillChoices: [{ options: 'any', rank: 'trained' }], redundantFallback: true },
  'mortal-possibility': { skillChoices: [{ options: 'any', rank: 'legendary' }] },
  'mountain-skin': { armor: { medium: 'trained', heavy: 'trained' } },
  'munitions-crafter': { skills: { crafting: 'trained' } },
  'nagaji-lore': { skills: { occultism: 'trained', crafting: 'trained', 'lore:naga': 'trained' }, loreChoices: 1, redundantFallback: true },
  'nantambu-chime-ringer-dedication': { skillChoices: [{ options: ['arcana', 'occultism'], rank: 'trained', conditionalRank: { base: 'trained', upgraded: 'expert' } }] },
  'natural-performer': { skills: { performance: 'trained' } },
  'natural-skill': { skillChoices: [{ options: 'any', rank: 'trained' }, { options: 'any', rank: 'trained' }] },
  'nephilim-lore': { skills: { religion: 'trained' }, skillChoices: [{ options: 'any', rank: 'trained' }], redundantFallback: true },
  'nosois-mask': { skills: { intimidation: 'trained' }, redundantFallback: true },
  'occult-dragonblood': { skills: { occultism: 'trained' }, redundantFallback: true },
  'occult-evolution': { skillChoices: [{ options: 'any', rank: 'trained' }] },
  'officers-education': { skillChoices: [{ options: 'any', rank: 'trained' }, { options: 'any', rank: 'trained' }, { options: 'any', rank: 'expert' }] },
  'officers-expertise': { skills: { 'lore:warfare': 'expert' } },
  'officers-mastery': { skills: { 'lore:warfare': 'master' } },
  'officers-medical-training': { skills: { medicine: 'trained' }, redundantFallback: true },
  'old-soul': { skillChoices: [{ options: 'any', rank: 'trained' }, { options: 'any', rank: 'trained' }] },
  'oozemorph-dedication': { skills: { 'lore:ooze': 'trained' }, conditionalSkills: { occultism: { base: 'trained', upgraded: 'expert' } }, redundantFallback: true },
  'operatic-adventurer': { skills: { performance: 'master' }, conditionalSkills: { 'lore:theater': { base: 'expert', upgraded: 'master' } }, rankUpgrade: { level: 15, rank: 'legendary' } },
  'oracle-dedication': { skills: { religion: 'trained' }, skillChoices: [{ options: 'any', rank: 'trained' }], redundantFallback: true },
  'orc-lore': { skills: { athletics: 'trained', survival: 'trained', 'lore:orc': 'trained' }, redundantFallback: true },
  'orc-warmask': { skillChoices: [{ options: ['religion', 'nature', 'arcana', 'occultism'], rank: 'trained' }] },
  'ostilli-host-dedication': { skills: { 'lore:ostilli': 'trained' } },
  'overlooked-mastermind': { skills: { deception: 'trained' }, redundantFallback: true },
  'pactbinder-dedication': { skills: { diplomacy: 'expert' }, skillChoices: [{ options: ['arcana', 'nature', 'occultism', 'religion'], rank: 'expert' }] },
  'past-life': { skillChoices: [{ options: 'any', rank: 'trained' }], redundantFallback: true },
  'pathfinder-agent-dedication': { conditionalSkills: { 'lore:pathfinder': { base: 'trained', upgraded: 'expert' } }, skillChoices: [{ options: 'any', rank: 'trained' }] },
  'pelagic-aptitude': { skills: { survival: 'trained' } },
  'physical-training': { skills: { acrobatics: 'master', athletics: 'master' } },
  'pirate-dedication': { skills: { 'lore:sailing': 'trained' } },
  'pitborn': { skills: { athletics: 'trained' }, redundantFallback: true },
  'prairie-rider': { skills: { nature: 'trained' }, redundantFallback: true },
  'primal-dragonblood': { skills: { nature: 'trained' }, redundantFallback: true },
  'progenitor-lore': { skills: { deception: 'trained', occultism: 'trained' }, loreChoices: 1, redundantFallback: true },
  'prophet-of-kalistrade-dedication': { skills: { society: 'expert' } },
  'provocator-dedication': { skills: { performance: 'expert' }, skillChoices: [{ options: ['acrobatics', 'athletics'], rank: 'expert' }], weapon: { simple: 'trained', martial: 'trained' } },
  'psychic-dedication': { skills: { occultism: 'trained' }, redundantFallback: true },
  'pure-legion-enforcer-dedication': { conditionalSkills: { intimidation: { base: 'trained', upgraded: 'expert' }, religion: { base: 'trained', upgraded: 'expert' } }, redundantFallback: true },
  'quah-bond': { skillChoices: [{ options: 'any', rank: 'trained' }], redundantFallback: true },
  'quicksoul': { skills: { acrobatics: 'trained' }, redundantFallback: true },
  'ranger-dedication': { skills: { survival: 'trained' }, redundantFallback: true },
  'ratfolk-lore': { skills: { acrobatics: 'trained', stealth: 'trained', 'lore:ratfolk': 'trained' }, redundantFallback: true },
  'red-mantis-assassin-dedication': { conditionalSkills: { stealth: { base: 'trained', upgraded: 'expert' }, 'lore:assassin': { base: 'trained', upgraded: 'expert' } } },
  'remnants-of-the-past': { loreChoices: 1 },
  'riftmarked': { skills: { occultism: 'trained' }, redundantFallback: true },
  'rivethun-emissary-dedication': { skills: { diplomacy: 'expert', religion: 'expert' } },
  'rivethun-invoker-dedication': { skills: { athletics: 'expert', religion: 'expert' } },
  'rivethun-involutionist-dedication': { skills: { nature: 'expert', religion: 'expert' } },
  'rose-warden-dedication': { conditionalSkills: { deception: { base: 'trained', upgraded: 'expert' } } },
  'round-ears': { skills: { deception: 'trained' }, redundantFallback: true },
  'ru-shi': { skills: { society: 'trained' }, redundantFallback: true },
  'runescarred-dedication': { skills: { arcana: 'expert' }, conditionalSkills: { 'lore:thassilon': { base: 'trained', upgraded: 'expert' } } },
  'sage-of-scattered-leaves': { skills: { religion: 'trained', nature: 'trained', 'lore:yaksha': 'trained' }, redundantFallback: true },
  'samsaran-lore': { skills: { religion: 'trained', society: 'trained', 'lore:samsaran': 'trained' }, redundantFallback: true },
  'sarangay-lore': { skills: { nature: 'trained', survival: 'trained', 'lore:sarangay': 'trained' }, redundantFallback: true },
  'scholars-inheritance': { skills: { crafting: 'trained' }, redundantFallback: true },
  'seasong': { skills: { performance: 'trained' }, redundantFallback: true },
  'shieldmarshal-dedication': { conditionalSkills: { society: { base: 'trained', upgraded: 'expert' } } },
  'shisk-lore': { skills: { 'lore:shisk': 'trained' }, loreChoices: 3 },
  'shokis-argument': { skills: { diplomacy: 'trained' }, redundantFallback: true },
  'shoony-lore': { skills: { diplomacy: 'trained', survival: 'trained', 'lore:shoony': 'trained' }, redundantFallback: true },
  'shrouded-mien': { skills: { deception: 'trained' }, redundantFallback: true },
  'silent-stone': { skills: { stealth: 'trained' }, redundantFallback: true },
  'sinister-appearance': { skills: { intimidation: 'trained' }, redundantFallback: true },
  'sister-of-the-golden-erinys-dedication': { skills: { 'lore:devil': 'trained' } },
  'sixth-pillar-dedication': { skillChoices: [{ options: 'any', rank: 'expert' }] },
  'skill-mastery': { skillChoices: [{ options: 'any', rank: 'master' }, { options: 'any', rank: 'expert' }] },
  'skill-mastery-rogue': { skillChoices: [{ options: 'any', rank: 'master' }, { options: 'any', rank: 'expert' }] },
  'skill-training': { skillChoices: [{ options: 'any', rank: 'trained' }] },
  'skull-creeper': { skills: { intimidation: 'trained' }, redundantFallback: true },
  'snare-setter': { skills: { crafting: 'trained' }, redundantFallback: true },
  'sociable': { skills: { diplomacy: 'trained' }, redundantFallback: true },
  'sorcerer-dedication': { skillChoices: [{ options: 'any', rank: 'trained' }, { options: 'any', rank: 'trained' }], redundantFallback: true },
  'spellshot-dedication': { skills: { arcana: 'trained' }, redundantFallback: true },
  'spiritual-echo': { loreChoices: 1 },
  'stalker-in-darkened-boughs': { skills: { 'lore:forest': 'trained', 'lore:hunting': 'trained' } },
  'startling-appearance-fleshwarp': { skills: { intimidation: 'trained' }, redundantFallback: true },
  'steward-of-stone-and-fire': { skills: { 'lore:mountain': 'trained', 'lore:volcano': 'trained' } },
  'stonebound-dedication': { skills: { 'lore:plane-of-earth': 'trained' }, redundantFallback: true },
  'stonemasons-eye': { skills: { crafting: 'trained' }, redundantFallback: true },
  'story-crooner': { skills: { performance: 'trained' }, redundantFallback: true },
  'strix-lore': { skills: { acrobatics: 'trained', nature: 'trained', 'lore:strix': 'trained' }, redundantFallback: true },
  'student-of-perfection-dedication': { conditionalSkills: { 'lore:warfare': { base: 'trained', upgraded: 'expert' } }, skillChoices: [{ options: ['acrobatics', 'athletics'], rank: 'trained' }] },
  'suli-jann': { skills: { survival: 'trained' }, redundantFallback: true },
  'surface-culture': { skills: { society: 'trained' }, loreChoices: 1, redundantFallback: true },
  'surki-lore': { skills: { survival: 'trained' }, skillChoices: [{ options: 'any', rank: 'trained' }], redundantFallback: true },
  'svetocher': { skills: { diplomacy: 'trained' }, redundantFallback: true },
  'swashbuckler-dedication': { skillChoices: [{ options: 'any', rank: 'trained' }], redundantFallback: true },
  'tangle-of-limbs': { skills: { athletics: 'trained' }, redundantFallback: true },
  'tanuki-lore': { skills: { deception: 'trained', performance: 'trained', 'lore:tanuki': 'trained' }, redundantFallback: true },
  'tattooed-historian-dedication': { skillChoices: [{ options: ['diplomacy', 'performance'], rank: 'trained' }], redundantFallback: true },
  'tengu-lore': { skills: { society: 'trained', survival: 'trained', 'lore:tengu': 'trained' }, redundantFallback: true },
  'thaumaturge-dedication': { skillChoices: [{ options: 'any', rank: 'trained' }], redundantFallback: true },
  'tinkering-fingers': { skills: { crafting: 'trained' }, redundantFallback: true },
  'transposable-compliance': { skills: { medicine: 'trained' }, redundantFallback: true },
  'travelers-counsel': { skills: { diplomacy: 'trained' }, redundantFallback: true },
  'trick-driver-dedication': { skills: { 'lore:driving': 'expert' } },
  'tripkee-lore': { skills: { nature: 'trained', stealth: 'trained', 'lore:tripkee': 'trained' }, redundantFallback: true },
  'turpin-rowe-lumberjack-dedication': { conditionalSkills: { 'lore:milling': { base: 'trained', upgraded: 'expert' }, 'lore:forest': { base: 'trained', upgraded: 'expert' } } },
  'twilight-speaker-dedication': { skills: { society: 'expert' }, rankUpgrade: { level: 7, rank: 'master' } },
  'twilight-talon-dedication': { skills: { 'lore:espionage': 'trained' } },
  'ulfen-guard-dedication': { skills: { 'lore:warfare': 'trained' } },
  'undead-slayer-dedication': { loreChoices: 2 },
  'undersea-privateer-dedication': { skills: { athletics: 'expert' } },
  'underworld-investigator': { skills: { 'lore:underworld': 'trained' } },
  'vampire-lore': { skills: { society: 'trained', religion: 'trained', 'lore:vampire': 'trained' }, redundantFallback: true },
  'vanara-lore': { skills: { survival: 'trained', thievery: 'trained', 'lore:vanara': 'trained' }, redundantFallback: true },
  'vanara-weapon-expertise': { weaponFamiliarity: {'weapons':['bo-staff','chakram','katar','panabas','urumi','gada'],'mirrorBestCategory':true} },
  'vandal': { skills: { thievery: 'trained' }, redundantFallback: true },
  'vanguard-of-roaring-waters': { skills: { 'lore:mountain': 'trained', 'lore:river': 'trained' } },
  'vehicle-mechanic-dedication': { skills: { crafting: 'expert' } },
  'verduran-shadow-dedication': { skills: { survival: 'expert' } },
  'viking-dedication': { skills: { 'lore:sailing': 'trained', 'lore:warfare': 'trained' } },
  'vishkanya-lore': { skills: { performance: 'trained', stealth: 'trained', 'lore:vishkanya': 'trained' }, redundantFallback: true },
  'vishkanya-weapon-expertise': { weaponFamiliarity: {'weapons':['blowgun','fighting-fan','kris','kukri','shuriken','visap'],'mirrorBestCategory':true} },
  'wandering-chef-dedication': { skills: { crafting: 'trained' }, redundantFallback: true },
  'war-mage-dedication': { skills: { 'lore:warfare': 'trained' } },
  'warpriests-armor': { rankUpgrade: { level: 13, rank: 'expert' }, armor: { heavy: 'trained' } },
  'warren-navigator': { skills: { survival: 'trained' }, redundantFallback: true },
  'wayang-lore': { skills: { performance: 'trained', stealth: 'trained', 'lore:wayang': 'trained' }, redundantFallback: true },
  'weight-of-experience': { skillChoices: [{ options: 'any', rank: 'trained' }] },
  'well-met-traveler': { skills: { diplomacy: 'trained' }, redundantFallback: true },
  'wild-mimic-dedication': { skills: { 'lore:wild-mimic': 'trained' } },
  'wisdom-from-another-life': { skillChoices: [{ options: 'any', rank: 'trained' }] },
  'witch-dedication': { skillChoices: [{ options: 'any', rank: 'trained' }], redundantFallback: true },
  'wizard-dedication': { skills: { arcana: 'trained' }, redundantFallback: true },
  'woodworker': { skills: { crafting: 'trained' }, redundantFallback: true },
  'wrestler-dedication': { skills: { athletics: 'expert' } },
  'wylderheart-dedication': { skills: { 'lore:demon': 'trained' } },
  'yaoguai-historian': { skills: { occultism: 'trained', 'lore:yaoguai': 'trained' }, redundantFallback: true },
  'youre-so-cute': { skills: { performance: 'trained' } },
  'zephyr-guard-dedication': { conditionalSkills: { society: { base: 'trained', upgraded: 'expert' }, 'lore:katapesh': { base: 'trained', upgraded: 'expert' } } },
};
