/*
 * Feats/features that GRANT a fixed bonus feat — auto-extracted from Foundry GrantItem rule elements
 * (unconditional GrantItem → a specific feats-srd item). buildCharacter adds each granted feat as a
 * BONUS (no slot consumed), transitively, so the granted feat shows in Feats & Features AND its own
 * effects apply (proficiency grants, further feat grants, situational bonuses). Deduped against feats
 * the character already has. Choice-based grants (General Training → "pick a general feat") are NOT
 * here — those need a builder picker and are a separate follow-up.
 *
 * Regenerate: scratch featfeat-extract.mjs. Every listed target is verified to ship in core.json.
 *
 * FEAT_FEAT_GRANTS_LEVELED (hand-authored, above the auto table so the apply scripts preserve it) is
 * for grants that only kick in at a HIGHER level (Covet Hoard → Incredible Investiture at 11th).
 */
export const FEAT_FEAT_GRANTS_LEVELED: Record<string, { feat: string; minLevel: number }[]> = {
  'covet-hoard': [{ feat: 'incredible-investiture', minLevel: 11 }],
};

export const FEAT_FEAT_GRANTS: Record<string, string[]> = {
  'alchemist-dedication': ['alchemical-crafting'],
  'alkenstar-agent-dedication': ['lie-to-me'],
  'anchoring-roots': ['steady-balance'],
  'angelkin': ['multilingual'],
  'arcane-dragonblood': ['arcane-sense'],
  'artisanal-crafter': ['specialty-crafting'],
  'as-in-life-so-in-death': ['adopted-ancestry'],
  'athamaru-lore': ['additional-lore'],
  'automaton-lore': ['additional-lore'],
  'awakened-animal-lore': ['additional-lore'],
  'bastion-dedication': ['reactive-shield'],
  'battle-harbinger-dedication': ['toughness'],
  'battleblooded': ['intimidating-glare'],
  'beast-trainer': ['train-animal'],
  'beastbrood': ['courtly-graces'],
  'beneath-notice': ['quick-disguise', 'slippery-secrets'],
  'blackjacket-dedication': ['additional-lore'],
  'break-the-cycle': ['legendary-negotiation'],
  'callow-may': ['charming-liar'],
  'catch-the-details': ['eye-for-numbers'],
  'centaur-lore': ['additional-lore'],
  'ceremony-of-knowledge': ['untrained-improvisation'],
  'chelaxian-scion-dedication': ['additional-lore'],
  'clever-improviser': ['untrained-improvisation'],
  'climbing-tail': ['combat-climber'],
  'command-corpse': ['command-undead'],
  'contortionist': ['quick-squeeze'],
  'covet-hoard': ['hefty-hauler'],
  'cultural-adaptability': ['adopted-ancestry'],
  'cutting-rebuke': ['bon-mot'],
  'deceptive-tactics': ['lengthy-diversion'],
  'dedication-to-the-five': ['domain-initiate'],
  'defenders-grit': ['diehard'],
  'draconic-acolyte-dedication': ['additional-lore'],
  'draconic-familiar': ['pet'],
  'dragon-lore': ['additional-lore'],
  'dragonscaled-lore': ['additional-lore'],
  'dual-weapon-warrior-dedication': ['double-slice'],
  'duelist-dedication': ['quick-draw'],
  'eagle-knight-dedication': ['additional-lore'],
  'earned-glory': ['impressive-performance'],
  'edgewatch-detective-dedication': ['experienced-tracker'],
  'eidetic-ear': ['assurance'],
  'elemental-existence': ['adopted-ancestry'],
  'elemental-trade': ['specialty-crafting'],
  'elude-the-divine': ['slippery-secrets'],
  'elver-pet': ['pet'],
  'embodied-dreadnought-subjectivity': ['hefty-hauler'],
  'engine-bay': ['quick-repair'],
  'enigmas-knowledge': ['automatic-knowledge'],
  'eye-for-treasure': ['crafters-appraisal'],
  'familiar-sage-dedication': ['enhanced-familiar'],
  'firework-technician-dedication': ['alchemical-crafting'],
  'gear-up': ['prescient-planner', 'prescient-consumable'],
  'gemsoul': ['impressive-performance'],
  'gray-corsair-training': ['pirate-dedication'],
  'greenwatch-initiate': ['experienced-tracker', 'survey-wildlife'],
  'grimspawn': ['diehard'],
  'harmlessly-cute': ['shameless-request'],
  'hellbreaker-dedication': ['additional-lore'],
  'hellspawn': ['lie-to-me'],
  'heroic-scion-dedication': ['additional-lore'],
  'hidden-intentions': ['doublespeak', 'slippery-secrets'],
  'horizon-walker-dedication': ['favored-terrain'],
  'i-will-return': ['diehard'],
  'ice-crafter': ['magical-crafting'],
  'idyllkin': ['natural-medicine'],
  'intuitive-crafting': ['specialty-crafting'],
  'inventor-dedication': ['inventor'],
  'jotunborn-grappler': ['titan-wrestler'],
  'juggler-dedication': ['juggle'],
  'kholo-lore': ['additional-lore'],
  'lastwall-sentry-dedication': ['reactive-shield'],
  'laughing-kholo': ['battle-cry'],
  'libertys-promise': ['domain-initiate'],
  'linguist-dedication': ['multilingual'],
  'merfolk-lore': ['additional-lore'],
  'meticulous-restorer': ['quick-repair'],
  'miresoul': ['quick-squeeze'],
  'moray-eel-mount': ['bonded-animal'],
  'mummy-dedication': ['toughness'],
  'munitions-crafter': ['alchemical-crafting'],
  'nephilim-lore': ['additional-lore'],
  'nosois-mask': ['intimidating-glare'],
  'occult-dragonblood': ['oddity-identification'],
  'officers-medical-training': ['battle-medicine'],
  'orc-warmask': ['dubious-knowledge'],
  'pack-stalker': ['terrain-stalker'],
  'past-life': ['additional-lore'],
  'patch-job': ['improvised-repair'],
  'perfect-weaponry': ['monastic-weaponry'],
  'pistol-phenom-dedication': ['pistol-twirl'],
  'plummeting-roll': ['cat-fall'],
  'poisoner-dedication': ['alchemical-crafting'],
  'predictive-purchase-rogue': ['prescient-planner', 'prescient-consumable'],
  'pure-legion-enforcer-dedication': ['recognize-spell'],
  'quah-bond': ['assurance'],
  'quick-fix': ['rapid-affixture'],
  'remnants-of-the-past': ['adopted-ancestry', 'additional-lore'],
  'reptile-rider': ['ride'],
  'riftmarked': ['oddity-identification'],
  'rivethun-invoker-dedication': ['diehard'],
  'rough-rider': ['ride'],
  'ru-shi': ['eye-for-numbers'],
  'runtsage': ['adopted-ancestry'],
  'sage-of-scattered-leaves': ['additional-lore'],
  'samsaran-lore': ['additional-lore'],
  'sarangay-lore': ['additional-lore'],
  'scholars-inheritance': ['alchemical-crafting'],
  'scroll-trickster-dedication': ['trick-magic-item'],
  'seasong': ['virtuosic-performer'],
  'seeker-of-truths': ['domain-initiate'],
  'seneschal-witch-dedication': ['witchs-charge'],
  'settlement-scholastics': ['additional-lore'],
  'seven-changes-performance': ['quick-disguise'],
  'shackleborn': ['fast-recovery'],
  'shieldmarshal-dedication': ['streetwise', 'courtly-graces'],
  'shiny-button-eyes': ['canny-acumen'],
  'shrouded-mien': ['lengthy-diversion'],
  'silent-stone': ['terrain-stalker'],
  'sinister-appearance': ['intimidating-glare'],
  'skilled-herbalist': ['alchemical-crafting'],
  'skull-creeper': ['intimidating-glare'],
  'slip-with-the-breeze': ['quick-jump', 'powerful-leap'],
  'slither': ['quick-squeeze'],
  'snare-expert': ['snare-crafting'],
  'snare-setter': ['snare-crafting'],
  'snarecrafter-dedication': ['snare-crafting'],
  'sociable': ['hobnobber'],
  'speak-for-the-gravelands': ['geomancer-dedication'],
  'spell-acceleration': ['quickened-casting'],
  'spirit-familiar-animist': ['pet'],
  'startling-appearance-fleshwarp': ['intimidating-glare'],
  'story-crooner': ['impressive-performance'],
  'student-of-perfection-dedication': ['qi-spells'],
  'suli-jann': ['forager'],
  'surface-culture': ['additional-lore'],
  'surki-lore': ['additional-lore'],
  'surreptitious-spellcaster': ['conceal-spell'],
  'tangle-of-limbs': ['titan-wrestler'],
  'tanuki-lore': ['additional-lore'],
  'terrain-scout': ['terrain-stalker'],
  'thaumaturges-investiture': ['incredible-investiture'],
  'three-clear-breaths': ['breath-control', 'diehard', 'fast-recovery'],
  'tripkee-lore': ['additional-lore'],
  'twilight-talon-dedication': ['additional-lore'],
  'ulfen-guard-dedication': ['additional-lore'],
  'uncanny-agility': ['steady-balance'],
  'uncanny-cheeks': ['prescient-consumable', 'prescient-planner'],
  'underbrush-trailblazer': ['terrain-stalker'],
  'undersea-privateer-dedication': ['underwater-marauder'],
  'veil-may': ['lie-to-me'],
  'vestigial-wings': ['steady-balance', 'cat-fall'],
  'viking-shieldbearer': ['shield-block'],
  'viking-vindicator': ['sudden-charge'],
  'viking-weapon-familiarity': ['shield-block'],
  'wandering-chef-dedication': ['alchemical-crafting'],
  'water-nagaji': ['breath-control'],
  'wayang-lore': ['additional-lore'],
  'we-march-on': ['caravan-leader', 'pick-up-the-pace'],
  'web-weaver': ['specialty-crafting'],
  'weight-of-experience': ['assurance'],
  'well-met-traveler': ['hobnobber'],
  'werecreature-dedication': ['toughness'],
  'whitecape': ['steady-balance'],
  'wind-pillow': ['powerful-leap'],
  'wisdom-from-another-life': ['additional-lore'],
  'woodworker': ['specialty-crafting'],
  'wrestler-dedication': ['titan-wrestler'],
  'youre-so-cute': ['impressive-performance'],
  'adaptive-anadi': ['adopted-ancestry'],
  'alchemical-scholar': ['alchemical-crafting'],
  'alchemical-sciences-methodology': ['alchemical-crafting'],
  'alchemy': ['alchemical-crafting'],
  'aloof-firmament': ['cat-fall'],
  'anvil-dwarf': ['specialty-crafting'],
  'appraisers-eye': ['quick-identification'],
  'artisan-android': ['specialty-crafting'],
  'battle-ready-orc': ['intimidating-glare'],
  'battledancer': ['fascinating-performance'],
  'catfolk-lore': ['additional-lore'],
  'caveclimber-kobold': ['combat-climber'],
  'changeling-lore': ['additional-lore'],
  'cliffscale-lizardfolk': ['combat-climber'],
  'compact-skeleton': ['quick-squeeze'],
  'creative-prodigy': ['impressive-performance'],
  'deep-orc': ['terrain-expertise', 'combat-climber'],
  'duskwalker-lore': ['additional-lore'],
  'dwarven-lore': ['additional-lore'],
  'elven-lore': ['additional-lore'],
  'empiricism-methodology': ['thats-odd'],
  'empty-sky-kitsune': ['kitsune-spell-familiarity'],
  'esoteric-lore': ['dubious-knowledge'],
  'first-doctrine-cloistered-cleric': ['domain-initiate'],
  'forensic-medicine-methodology': ['forensic-acumen', 'battle-medicine'],
  'frightful-goloma': ['intimidating-glare'],
  'full-moon-sarangay': ['folk-healer'],
  'geckos-grip': ['combat-climber'],
  'gladiator-dedication': ['additional-lore'],
  'gnome-obsession': ['additional-lore', 'assurance'],
  'goblin-lore': ['additional-lore'],
  'halfling-lore': ['additional-lore'],
  'hobgoblin-lore': ['additional-lore'],
  'hold-scarred-orc': ['diehard'],
  'initiate-benefit-shield': ['shield-block'],
  'interrogation-methodology': ['no-cause-for-alarm'],
  'jalmeri-heavenseeker-dedication': ['qi-spells'],
  'keeper-jotunborn': ['survey-wildlife'],
  'kobold-lore': ['additional-lore'],
  'laborer-android': ['hefty-hauler'],
  'leshy-lore': ['additional-lore'],
  'listeners-boon': ['domain-initiate'],
  'liturgist': ['circle-of-spirits'],
  'lizardfolk-lore': ['additional-lore'],
  'marine-marauder-dedication': ['underwater-marauder'],
  'medium': ['relinquish-control'],
  'minotaur-lore': ['additional-lore'],
  'nine-lives-catfolk': ['diehard'],
  'peerless-inventor': ['inventor'],
  'pine-leshy': ['combat-climber'],
  'pirate-dedication': ['additional-lore'],
  'polychromatic-anadi': ['impressive-performance'],
  'prismatic-vishkanya': ['fascinating-performance'],
  'rascal': ['dirty-trick'],
  'ratfolk-lore': ['additional-lore'],
  'respite-of-a-thousand-roofs': ['improvise-tool'],
  'roaming-minotaur': ['terrain-expertise'],
  'runtboss-hobgoblin': ['group-coercion'],
  'sage-jotunborn': ['additional-lore'],
  'scavenger-strix': ['forager'],
  'seer': ['apparition-sense'],
  'shadow-of-the-courtier': ['impressive-performance'],
  'shield': ['shield-block'],
  'shield-block': ['shield-block'],
  'shoreline-strix': ['underwater-marauder'],
  'shortshanks-hobgoblin': ['ride'],
  'sister-of-the-golden-erinys-dedication': ['additional-lore'],
  'sparkling-targe': ['shield-block'],
  'spellbook-prodigy': ['magical-shorthand'],
  'stalker-minotaur': ['terrain-stalker'],
  'sturdy-skeleton': ['diehard'],
  'summiting-dragonblood': ['combat-climber'],
  'surgewise-fleshwarp': ['oddity-identification'],
  'tengu-lore': ['additional-lore'],
  'thalassic-azarketi': ['underwater-marauder'],
  'tough-to-kill': ['diehard'],
  'trogloshi': ['crystal-luminescence'],
  'tunnel-rat': ['quick-squeeze'],
  'vampire-lore': ['additional-lore'],
  'viking-dedication': ['additional-lore'],
  'war-mage-dedication': ['additional-lore'],
  'wisp-fetchling': ['quick-squeeze'],
  'wit': ['bon-mot'],
  'woodstalker-lizardfolk': ['terrain-stalker'],
  'yaoguai-historian': ['additional-lore'],
};
