/*
 * The active content database.
 *
 * The imported game data (generated by scripts/import-core.mjs, all books, ~14 MB)
 * lives in public/core.json and is FETCHED at runtime rather than bundled into the
 * JS — at this size, inlining it via `?raw` would bloat the bundle and slow startup.
 * On load we merge the hand-authored seed underneath it: Core is canonical, the seed
 * fills any gaps (so the example character keeps resolving even where Core lacks an
 * exact slug).
 */
import type { ContentDatabase } from '../rules/types';
import { seedContent } from '../rules/seed';
import { CATALOG_MODE_MAP } from '../rules/modes';
import { loadHomebrewItems, loadModes } from './storage';

function merge<T>(base: Record<string, T>, over: Record<string, T>): Record<string, T> {
  return { ...base, ...over };
}

function mergeWithSeed(core: Partial<ContentDatabase>): ContentDatabase {
  const c = core as ContentDatabase;
  return {
    ancestries: merge(seedContent.ancestries, c.ancestries ?? {}),
    heritages: merge(seedContent.heritages, c.heritages ?? {}),
    backgrounds: merge(seedContent.backgrounds, c.backgrounds ?? {}),
    classes: merge(seedContent.classes, c.classes ?? {}),
    classFeatures: merge(seedContent.classFeatures, c.classFeatures ?? {}),
    feats: merge(seedContent.feats, c.feats ?? {}),
    spells: merge(seedContent.spells, c.spells ?? {}),
    // Core/seed first, then the user's custom (homebrew) items on top.
    items: merge(merge(seedContent.items, c.items ?? {}), loadHomebrewItems()),
    deities: merge(seedContent.deities, c.deities ?? {}),
    languages: merge(seedContent.languages, c.languages ?? {}),
    animalCompanions: merge(seedContent.animalCompanions, c.animalCompanions ?? {}),
    familiarAbilities: merge(seedContent.familiarAbilities, c.familiarAbilities ?? {}),
    companionSpecializations: merge(seedContent.companionSpecializations ?? {}, c.companionSpecializations ?? {}),
    followers: merge(seedContent.followers ?? {}, c.followers ?? {}),
    pets: merge(seedContent.pets ?? {}, c.pets ?? {}),
    services: merge(seedContent.services ?? {}, c.services ?? {}),
    vehicles: merge(seedContent.vehicles ?? {}, c.vehicles ?? {}),
    siegeWeapons: merge(seedContent.siegeWeapons ?? {}, c.siegeWeapons ?? {}),
    conditions: merge(seedContent.conditions, c.conditions ?? {}),
    actions: merge(seedContent.actions, c.actions ?? {}),
    // Built-in mode catalog, then the user's saved modes on top.
    modes: merge(CATALOG_MODE_MAP, loadModes()),
    runes: c.runes ?? {},
  };
}

let cached: ContentDatabase | null = null;

/** Fetch + parse public/core.json once, merged with the seed. Cached after first call. */
export async function loadContent(): Promise<ContentDatabase> {
  if (cached) return cached;
  try {
    const res = await fetch(`${import.meta.env.BASE_URL}core.json`);
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    const core = (await res.json()) as Partial<ContentDatabase>;
    cached = mergeWithSeed(core);
  } catch (err) {
    // Fall back to the seed alone so the app still boots (and the example
    // character resolves) if the data file is missing or unreadable.
    console.error('Failed to load core.json; falling back to seed content.', err);
    cached = mergeWithSeed({});
  }
  return cached;
}
