/*
 * The active content database.
 *
 * The imported game data (generated by scripts/import-core.mjs, all books, ~14 MB)
 * lives in public/core.json and is FETCHED at runtime rather than bundled into the
 * JS — at this size, inlining it via `?raw` would bloat the bundle and slow startup.
 * On load we merge the hand-authored seed underneath it: Core is canonical, the seed
 * fills any gaps (so the example character keeps resolving even where Core lacks an
 * exact slug).
 */
import type { ContentDatabase, SourceInfo } from '../rules/types';
import { seedContent } from '../rules/seed';
import { CATALOG_MODE_MAP } from '../rules/modes';
import { loadHomebrewContent, loadHomebrewSources, loadModes, HOMEBREW_TYPES } from './storage';

function merge<T>(base: Record<string, T>, over: Record<string, T>): Record<string, T> {
  return { ...base, ...over };
}

/** Feats deliberately excluded from the app (per user decision) — dropped from content AFTER the merge,
 *  so they never appear in any picker or resolve as a grant. Applied here in the loader rather than in
 *  the data file, so the exclusion survives every core.json regeneration.
 *
 *  The tattoo CHAIN must be excluded together. `arcane-tattoos` was excluded on its own, which left
 *  `ornate-tattoo` (prerequisite "Arcane Tattoos") and, behind it, `virtue-forged-tattoos`
 *  (prerequisite "Ornate Tattoo") in the pickers with a prerequisite that can never be met — the
 *  parent no longer exists in the running database. Both also read "the same school as your Arcane
 *  Tattoos", a school the character can never have chosen. Excluding a feat means excluding whatever
 *  depends on it. */
export const EXCLUDED_FEATS = new Set(['arcane-tattoos', 'ornate-tattoo', 'virtue-forged-tattoos', 'hag-magic']);

/** Collections where an `aon-`-prefixed scrape can shadow an existing record of the same name. */
const DEDUPE_MAPS = ['items', 'feats', 'spells', 'actions', 'vehicles', 'backgrounds', 'heritages', 'deities'] as const;
const dedupeKey = (name: string) => name.toLowerCase().replace(/[^a-z0-9]/g, '');

/**
 * `aon-` duplicates the exact-name match walks straight past, because the scrape spelled the name
 * differently — "Historical Reeanactor" beside "Historical Reenactor".
 *
 * Scanning every `aon-` record for a canonical name within edit distance 2, then scoring the two
 * descriptions by word overlap, found 46 such pairs. 42 of them turned out to ALSO have an
 * exactly-named twin, so the rule above already hid them; listing those here would be 42 lines that
 * do nothing. The four below are the real holes, and all four are BACKGROUNDS — a collection that
 * was missing from DEDUPE_MAPS entirely.
 *
 * Not every near-miss is a duplicate: Minor vs Major Astonishing Ink, Magic Armor vs Magic Armor (+1),
 * the ten scroll ranks, Firearm Ammunition 5 vs 10 rounds, Searing vs Healing Wave and Shield Bash vs
 * Shield Boss all read alike and are distinct records. A similarity threshold alone cannot tell a
 * typo from a grade, which is why this list is curated rather than computed at load.
 *
 * Hidden, never deleted — same reason as the exact-name set: a saved character may already reference
 * one of these ids, and an id that vanishes takes the player's background with it.
 */
export const NEAR_DUPLICATE_IDS = new Set([
  'aon-historical-reeanactor', // -> historical-reenactor
  'aon-post-guard-of-all-trade', // -> post-guard-of-all-trades
  'aon-reclaimed-investigator', // -> reclaimer-investigator
  'aon-wishes-for-riches', // -> wish-for-riches
]);

/**
 * Ids of `aon-`-prefixed records that DUPLICATE a canonical record of the same name in the same
 * collection. An earlier scrape re-added content the app already had under a different id, so
 * pickers list many entries twice (408 item pairs, 100 actions, 81 feats, 91 Kingmaker rows…).
 *
 * These are HIDDEN FROM LISTS rather than deleted from the database. Deleting them would orphan any
 * saved character that already picked one (characters store raw ids — feats[].featId,
 * inventory[].itemId, spell slots…), and 149 other `aon-` records are the ONLY copy of their content
 * (72 animal companions, 37 vehicles, 14 conditions) so a blanket prefix rule would destroy real
 * data. Collision-only + hide-don't-delete keeps every existing reference resolvable.
 */
export function findDuplicateIds(db: ContentDatabase): Set<string> {
  const dupes = new Set<string>();
  for (const mapName of DEDUPE_MAPS) {
    const map = db[mapName] as unknown as Record<string, { name?: string }> | undefined;
    if (!map) continue;
    const canonical = new Set<string>();
    for (const [id, rec] of Object.entries(map)) {
      if (!rec?.name || id.startsWith('aon-')) continue;
      canonical.add(dedupeKey(rec.name));
    }
    for (const [id, rec] of Object.entries(map)) {
      // Only an `aon-` record that COLLIDES with a canonical twin is a duplicate; an `aon-` record
      // that is the sole copy of its content stays visible.
      if (id.startsWith('aon-') && rec?.name && canonical.has(dedupeKey(rec.name))) dupes.add(id);
    }
  }
  // The curated near-miss set: same content, different spelling, so the exact match above misses it.
  // Guarded on existence so a retired id never hides something that took its place.
  for (const id of NEAR_DUPLICATE_IDS) {
    for (const mapName of DEDUPE_MAPS) {
      if ((db[mapName] as unknown as Record<string, unknown> | undefined)?.[id]) dupes.add(id);
    }
  }
  return dupes;
}

/** True if `id` is a duplicate scrape that should be omitted from user-facing lists. */
export function isDuplicateId(content: ContentDatabase, id: string): boolean {
  return !!content.duplicateIds?.has(id);
}

/** `Object.values(map)` minus duplicate scrapes — use this for ANY list the user reads or picks
 *  from, so the same entry never appears twice. Direct `content.x[id]` lookups are untouched, so a
 *  character that already references a duplicate still resolves it. */
export function listValues<T>(content: ContentDatabase, map: Record<string, T>): T[] {
  const dupes = content.duplicateIds;
  if (!dupes?.size) return Object.values(map);
  const out: T[] = [];
  for (const id in map) if (!dupes.has(id)) out.push(map[id]);
  return out;
}

function mergeWithSeed(core: Partial<ContentDatabase>): ContentDatabase {
  const c = core as ContentDatabase;
  // Seed → Core → user homebrew, so homebrew entries resolve everywhere core content does.
  const hb = loadHomebrewContent();
  // Tag each homebrew entry's source.book with its Source's name, so the per-character Sources filter
  // (applySources) governs it: a homebrew Source is off by default and opt-in via Setup → Sources.
  const hbSources = loadHomebrewSources();
  for (const type of HOMEBREW_TYPES) {
    for (const entry of Object.values(hb[type]) as unknown as { homebrewSourceId?: string; source?: SourceInfo }[]) {
      const name = entry.homebrewSourceId ? hbSources[entry.homebrewSourceId]?.name : undefined;
      entry.source = { ...(entry.source ?? {}), license: 'homebrew', ...(name ? { book: name } : {}) };
    }
  }
  const db: ContentDatabase = {
    ancestries: merge(merge(seedContent.ancestries, c.ancestries ?? {}), hb.ancestries),
    heritages: merge(merge(seedContent.heritages, c.heritages ?? {}), hb.heritages),
    backgrounds: merge(merge(seedContent.backgrounds, c.backgrounds ?? {}), hb.backgrounds),
    classes: merge(seedContent.classes, c.classes ?? {}),
    classFeatures: merge(seedContent.classFeatures, c.classFeatures ?? {}),
    feats: merge(merge(seedContent.feats, c.feats ?? {}), hb.feats),
    spells: merge(merge(seedContent.spells, c.spells ?? {}), hb.spells),
    items: merge(merge(seedContent.items, c.items ?? {}), hb.items),
    deities: merge(seedContent.deities, c.deities ?? {}),
    languages: merge(seedContent.languages, c.languages ?? {}),
    animalCompanions: merge(seedContent.animalCompanions, c.animalCompanions ?? {}),
    familiarAbilities: merge(seedContent.familiarAbilities, c.familiarAbilities ?? {}),
    companionSpecializations: merge(seedContent.companionSpecializations ?? {}, c.companionSpecializations ?? {}),
    companionAdvanced: merge(seedContent.companionAdvanced ?? {}, c.companionAdvanced ?? {}),
    specificFamiliars: merge(seedContent.specificFamiliars ?? {}, c.specificFamiliars ?? {}),
    followers: merge(seedContent.followers ?? {}, c.followers ?? {}),
    pets: merge(seedContent.pets ?? {}, c.pets ?? {}),
    services: merge(seedContent.services ?? {}, c.services ?? {}),
    vehicles: merge(seedContent.vehicles ?? {}, c.vehicles ?? {}),
    siegeWeapons: merge(seedContent.siegeWeapons ?? {}, c.siegeWeapons ?? {}),
    conditions: merge(seedContent.conditions, c.conditions ?? {}),
    actions: merge(merge(seedContent.actions, c.actions ?? {}), hb.actions),
    // Built-in mode catalog, then the user's saved modes on top.
    modes: merge(CATALOG_MODE_MAP, loadModes()),
    stances: merge(seedContent.stances ?? {}, c.stances ?? {}),
    runes: c.runes ?? {},
  };
  for (const id of EXCLUDED_FEATS) delete db.feats[id];
  // Carry over any EXTRA buckets core ships that aren't in the explicit list above — the glossary/reference
  // buckets (rules, trait, source, skill, domain, class sub-options, …) whose only job is to let a
  // description cross-link resolve and open. They have no seed/homebrew layer, so a straight copy is right.
  const extra = db as unknown as Record<string, unknown>;
  const coreRec = c as unknown as Record<string, unknown>;
  for (const k in coreRec) if (!(k in db)) extra[k] = coreRec[k];
  // Computed last, so it sees seed + core + homebrew (homebrew never uses the `aon-` prefix, but a
  // homebrew entry CAN be the canonical twin that unmasks a duplicate).
  db.duplicateIds = findDuplicateIds(db);
  return db;
}

let cached: ContentDatabase | null = null;
let cachedCore: Partial<ContentDatabase> = {};
let pending: Promise<ContentDatabase> | null = null;

/** Re-merge seed + core + the current homebrew (re-read from storage) without re-fetching core.json.
 *  Call after the user edits homebrew so the live content DB reflects it immediately. */
export function rebuildContent(): ContentDatabase {
  cached = mergeWithSeed(cachedCore);
  return cached;
}

/** Fetch + parse public/core.json once, merged with the seed. Concurrent callers share the
 *  in-flight promise (main.tsx prefetches before React mounts; App awaits the same load). */
export function loadContent(): Promise<ContentDatabase> {
  if (cached) return Promise.resolve(cached);
  pending ??= (async () => {
    try {
      const res = await fetch(`${import.meta.env.BASE_URL}core.json`);
      if (!res.ok) throw new Error(`HTTP ${res.status}`);
      const core = (await res.json()) as Partial<ContentDatabase>;
      cachedCore = core;
      cached = mergeWithSeed(core);
    } catch (err) {
      // Fall back to the seed alone so the app still boots (and the example
      // character resolves) if the data file is missing or unreadable.
      console.error('Failed to load core.json; falling back to seed content.', err);
      cached = mergeWithSeed({});
    }
    return cached;
  })();
  return pending;
}
